### ISSUE TITLE
[Feature] Hiring and Firing capability for Judges, a DOJ duty log, lawyer clock in/out ability

### ISSUE THREAD

**Issue by brookie41** [FrenzyRoleplay/server-issues#103]
**Is your feature request related to a problem? Please describe.**
The problem would be bothering Codes for every Judge that needs to be hired or fired. We are implementing an hours requirement for all DOJ positions, but we cannot monitor the hours which is why a duty log would be helpful. Currently, lawyers do no clock in or out so we would not be able to monitor their hours at all even if there was a duty log.

**Describe the solution you'd like**
The ideal solution would be for Ariel Rose to have the hiring and firing ability for Judges in city.  Also, by having a duty log and all DOJ positions having to clock in and out, there would be more DOJ in city because they would need to get their hours in.  There would also be documentation that there actually are DOJ employees in city.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by katahtonic** [comment]
resolved
