### ISSUE TITLE
[Bug] MDT crashes with fatal error

### ISSUE THREAD

**Issue by unPhiltrd** [FrenzyRoleplay/server-issues#108]
**Describe the bug**
Searched for a person record in MDT, when I clicked on the person, MDT crashed to a "fatal error".

**To Reproduce**
1. open MDT by typing "t" and then "/mdt"
2. Search records by person name.
3. Once names are shown, click a record.
4. See error below (screenshot).

**Expected behavior**
I expected to see the person's record so I could check for DNA & fingerprints on file.

**Screenshots**
![20210119140148_1](https://user-images.githubusercontent.com/77427756/105098645-3a36e080-5a5f-11eb-9491-2e8311a6a5cb.jpg)

**Comment by katahtonic** [comment]
resolved
