### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by IveyJules** [FrenzyRoleplay/server-issues#112]
Last night I flew in and my inventory was completely gone. I ate a double double before stepping away, was gone for not to long but long enough for the AFK timer to kick me. The only thing I'm worried about as far as my inventory goes is my radio scanner, harness, and extended mag that was on my pistol. I had medical supply and food other than that but I've already replaced it :)

**Comment by katahtonic** [comment]
n/a - db wipe and new inventory
