### ISSUE TITLE
Can access clothing menu from outside pillbox [Bug] 

### ISSUE THREAD

**Issue by AngryBaconator** [FrenzyRoleplay/server-issues#116]
**Describe the bug**
I pulled up to pillbox and saw I was able to access the menu outside of pillbox

**To Reproduce**
Walk up to wall
Says press E to change clothes

**Expected behavior**
Not access it outside lol

**Screenshots**
![20210121001714_1](https://user-images.githubusercontent.com/45416172/105419575-8c653680-5c04-11eb-9360-5ae510c25232.jpg)

**Additional context**

**Comment by katahtonic** [comment]
issue resolved
