### ISSUE TITLE
Vehicle XA-21

### ISSUE THREAD

**Issue by Skywolfie** [FrenzyRoleplay/server-issues#12]
Describe the bug:
I recently bought myself the XA-21 car pricetag on it was 520,000 
drove it down the highway and bone stock the car only goes 105mph without upgrades.
appart from the speed, the car is amazing to drive.

**Comment by ItsMelnyk** [comment]
Ill reach out and see if we can get this vehicle adjusted!

**Comment by Skywolfie** [comment]
> Ill reach out and see if we can get this vehicle adjusted!

ok thanks, i just fully upgraded the car, level 3 engine, trans and suspension with turbo goes like 110-115mph lol

**Comment by badcodestv** [comment]
This has been updated in the most recent push.
