### ISSUE TITLE
weird items spawning..

### ISSUE THREAD

**Issue by Sgtkrisper** [FrenzyRoleplay/server-issues#124]
![image](https://user-images.githubusercontent.com/67704331/105646839-ab6dfd80-5e7c-11eb-94d0-7302d907b5cf.png)
 I'm in the prison and no matter where I stand random item's (fishing rod, liquor, food, note's, etc..) will spawn as a dropped item..

**Comment by katahtonic** [comment]
Fixed infinity issue for dropped items
