### ISSUE TITLE
[Bug] Able to see police/ems/doc blips after switching characters

### ISSUE THREAD

**Issue by yukisho** [FrenzyRoleplay/server-issues#126]
**Describe the bug**
Switched from police to not police

**To Reproduce**
1. Clock in as Police/EMS/DOC
2. Go to apartment and Logout
3. Switch to other character that is not of those jobs
4. See blips on map/radar

**Expected behavior**
Not see blips.

**Screenshots**
https://i.imgur.com/AjnW8ra.png

**Additional context**

**Comment by katahtonic** [comment]
issue resolved
