### ISSUE TITLE
[BUG] Flooded House Removal Request

### ISSUE THREAD

**Issue by theCitizen420** [FrenzyRoleplay/server-issues#13]
**Describe the bug**
Unpurchased home has water in it and would like it removed prior to someone purchasing it by chance. 

**To Reproduce**
1. Go to North Califa Way 1
2. Enter
3. Drown
4. Delete please <3

**Expected behavior**
Near water, so this is somewhat expected and just wanted it removed.

**Comment by badcodestv** [comment]
Resolved.
