### ISSUE TITLE
my pockets and Stash in house are bugged...

### ISSUE THREAD

**Issue by SirPotatoTV** [FrenzyRoleplay/server-issues#134]
Having issues with my pockets - Stash - and maybe just an item or 2.

First off - Repair kits have been bugged for me since arriving in the city. 
1st experience : I was at mega mall - bought 2 repair kits - left - when i reopened my pockets they were missing.
2nd experience : I had 1 repair kit left in my pocket in the 4 keybind/hotkey slot when i tried to buy 5 more from toolshop ON the freeway headed up to sandy/polito it wouldnt let me. I tried to buy just 1 then and stack it and still wouldnt let me. So then i tried to buy 1 and place in a different slot - it worked. I then left and opened my pocket to try and stack on top of the 1 in my keybind and error kept occurring. i reopened the shop - and bought 5 to stack on the 1 i previously just bought and wouldnt work. the only way it would work is if i sent it to a different slot. So at this point i had 7 repair kits in 3 different slots in my pockets- 1, 1, and 5.
As i was headed home to stash a couple repair kits - i used 1 to repair my truck - it took 1 out the the 5 stack.. So 6 repair kits in 3 slots reading 1, 1 and 4 in those slots. I got home and tried to put away few repair kits and switch my hotkey items around things got goofy. first it wouldnt let me move the repair kit out of the hotkey/keybind . i then decided to try and put them all in my stash and see if they will stack.. answer is nope - they didnt stack and thats when i i said - let me take a nap and see what happens. After flying back in - i was finally able to switch keybinded items and get the 1 toolkit into a different slot in my stash. I then went back to toolshop to get 5 more repair kits - after returning to my home - i put a few  of the repair kits in my stash and while moving i apparently Swapped my stack of 4 repair kits with the 307 steel i had accumulated but it didnt register right away. after i left my house and came back i opened my stash - i found that my 4 repair kit stack was lost and that it was in the slot i had my steel in and  it only registered 1 repair kit in that slot. the steel i had was registering as my toolkits with 4 only.. So i basically went from 307 steel and 4 repair kits to  4steel and 1 repair kit. Final total of my repair kits are 8 in four slots and will not stack in my stash reading in stacks of 1, 1 , 1, and 5. 

Swapping items - like the switching items around thing sometimes is buggy too. - I bought ingredients at the 24/7 didnt realize i stacked them on my fishing rod - My fishing rod then went to ingredient slot at the store... I then pulled fishing rod back to my pockets - it turned into another ingredient and i lost my fishing rod. 

Sorry i dont have any screenshots - recorded clips - i would normally stream too to be able to highlight everything that happened. So its basically just my word. 

I dont care about losing the stuff - losing out on few bucks - just want it fixed so doesnt keep happening to me and to other people.

**Comment by katahtonic** [comment]
n/a - db wipe new inventory
