### ISSUE TITLE
Script Error for Ellie Fuel[Bug] 

### ISSUE THREAD

**Issue by hhenry12** [FrenzyRoleplay/server-issues#135]
**Describe the bug**
There has been an issue with the fuel with the Ellie I've noticed for a while. This was before the major updates to the server. An example of this would be the Ellie fuel would not update after it hit 50 or a random number. It would change when you refuel it. 

**To Reproduce**
I would say to purchase the Ellie and drive around it. You should notice after a while the fuel does not update

**Expected behavior**
The fuel should change when using the car. But I provide a screenshot of the script error below

**Screenshots**
[Script Error](https://i.imgur.com/pT8OCeL.png)

**Additional context**
N/A

**Comment by cademullen** [comment]
This seems to be fixed.
