### ISSUE TITLE
[Bug] Tow truck Job menu not Persistent

### ISSUE THREAD

**Issue by Trauma-Llama** [FrenzyRoleplay/server-issues#136]
**Describe the bug**
Upon logging out and logging in the Tow truck job menu in F1 is removed. You still have the job but the menu is gone (May be the same for the taxi job as well Have not tested)

**To Reproduce**
1. Go to Job center
2. Get the Tow Job
3. Check and see you have Tow menu in F1
4. Relog and notice you are still Tow but no longer have F1 tow menu

**Comment by badcodestv** [comment]
Fixed on next restart
