### ISSUE TITLE
[Bug] Items disappeared when going to jail

### ISSUE THREAD

**Issue by sirknoe** [FrenzyRoleplay/server-issues#139]
I was in jail and had logged in and it had put me in my house I had removed some items from the stash at Forum 6 and noticed I didnt have my phone, id etc etc So I had /991 and /311 to be sent to prison for 1min to get my items back. I had received my items back from my intiial sentence, however, the items I had pulled from my stash before being resent to jail had gone! There was over 50 crypto I was about to trade in and some guns I was about to store.

I believe this was on the 29th there should be a Jail log of me going in for 1min

**Comment by Nussifer** [comment]
I have somewhat of the same issue but being pocket whipped when going to jail

**Comment by katahtonic** [comment]
n/a - db wipe
