### ISSUE TITLE
[Bug] First Person to Third Person Bug

### ISSUE THREAD

**Issue by ExoticMyth** [FrenzyRoleplay/server-issues#144]
**Describe the bug**
When in a car you can aim your gun and scroll up on your mouse wheel and it will put you back in 3rd person. 
**To Reproduce**
1. Go into a car
2. Have your gun out 
3. Aim your gun
4. Scroll up on the mouse wheel a few times until it puts you in 3rd person with your gun out

**Expected behavior**
You are only supposed to shoot in a car in first person. 
**Screenshots**

**Additional context**

**Comment by katahtonic** [comment]
issue resolved- no shooting out of cars
