### ISSUE TITLE
[Feature] Bandannas/drug sales 

### ISSUE THREAD

**Issue by itsdonz** [FrenzyRoleplay/server-issues#151]
ESR (green) are wanting to know when we will be able to get are colors like are bandannas in are pockets (inventory item) also wanting to see more green clothing in side the shops. im not sure how we would go about this but both male and females there is lmtd stuff for green. if there another way to go about this please send me in the right direction.. we are also wanting to no if we can possibly sell Weed up in the fudge area as this is were we hold are own block.

Thanks :)

**Comment by katahtonic** [comment]
added bandanas with many colors to clothing options
