### ISSUE TITLE
[Bug] BIGGG STASH MISSING

### ISSUE THREAD

**Issue by sirknoe** [FrenzyRoleplay/server-issues#154]
I have come into my stash that ONLY I have access too! ALL of my weed seeds have gone over 500 seeds of OG. 3-400 Skunk seeds 100+ White Widow seeds I only have 4/10 Dracos in my stash all my AR's are missing pump shotguns etc etc I dont know what has happened!?

**Comment by sirknoe** [comment]
https://www.twitch.tv/videos/897395622

**Comment by sirknoe** [comment]
![20210102022035_1](https://user-images.githubusercontent.com/71553685/106534154-53be3a80-64eb-11eb-89bf-aa4f8ca0be05.jpg)
![20210103011603_1](https://user-images.githubusercontent.com/71553685/106534156-54ef6780-64eb-11eb-8810-a91aa45da4e0.jpg)
![20210104181142_1](https://user-images.githubusercontent.com/71553685/106534158-54ef6780-64eb-11eb-91d5-d4022b9d2174.jpg)
This is I guess proof of my seed count?

**Comment by sirknoe** [comment]
UPDATE: All my stash has pretty much disappeared ALL my guns have gone so that's AK's, Dracos, APs, Heavys, Vintages, Pump shottys the lot. I've not even been in the city for days to do or move anything?

**Comment by AngryBaconator** [comment]
Taken care of. 

Ticket can be closed.
