### ISSUE TITLE
[Bug] Stuff Poofin out of stash

### ISSUE THREAD

**Issue by uksad** [FrenzyRoleplay/server-issues#155]
**Describe the bug**
Hiya, currently had alot of stuff go missing from my house in mirror park 1 - ive had the following vanish
1x AP Pistol
2x Trojan USB
600x Plastic
150x Steel
1x PD Heavy

**To Reproduce**
1. Go into inventory
2. Move Stuff
3. Come out of inventory
4. Vanished

**Expected behavior**
Would like a refund on all items lost if possible as its not alot but took a while to get, some belonging to others aswell

**Additional context**
This has happened twice wasnt aware it was a on going bug

**Comment by katahtonic** [comment]
n/a - db wipe
