### ISSUE TITLE
Housing and stash issues.

### ISSUE THREAD

**Issue by IveyJules** [FrenzyRoleplay/server-issues#156]
**Update: It seems we have also lost an AP and a taser from another one of our houses :(

Bay tree Cannon Rd #7+8 Both need to be demolished as the stashes seem to be getting mixed up. They need to be created one at a time.
Bay tree Cannon Rd #2 house interior has switched from the tailor interior 5 to interior 1. While we do like it we figured that it would be worth mentioning. 
 N. Rockford Dr #1 Things are missing from the stash. We are missing an AK with 25 magazines as well as 2 tasers. 

Figured it would just be easier to make one ticket about the issues :P 
Heres a picture of what happened to #2
![houseissue](https://user-images.githubusercontent.com/76711076/106707594-19ba6a80-65b7-11eb-89ba-ed9eecb4c520.png)

 Heres a picture of the AK and Mags, the tasers arent pictured but they were lost.
![houseissues1](https://user-images.githubusercontent.com/76711076/106707656-35257580-65b7-11eb-9728-e08f599a5efa.png)

**Comment by katahtonic** [comment]
n/a - db wipe
