### ISSUE TITLE
[BUG] Vehicle Payment Error

### ISSUE THREAD

**Issue by Boundbyanxiety** [FrenzyRoleplay/server-issues#16]
**Describe the bug**
I bought an Evo from someone and It tells me I have 8 payments left. It was previously owned by; Cheech, Lang, and Jacks. All 3 told me they have put 2 payments on it. And ive put 1 payment on it.
**To Reproduce**
1. Go to 'phone'
2. Click on 'vehicles'
3. Scroll down to 'the evo'
of 8 payments left. 
**Expected behavior**
A clear and concise description of what you expected to happen.|
There should only be 5 payments left on the Evo instead of 8

**Screenshots**
https://gyazo.com/0514e02fbe89ee1ad8a60c7e993f20f3

**Additional context**

**Comment by Boundbyanxiety** [comment]
Would like to add that I will be on vacation from 12/25/2020 through 01/05/2021. So this may be something that will have to wait to be resolved till then.

**Comment by Boundbyanxiety** [comment]
Just put my second payment on it. After looking back at the math... there should only be 2 more payments if all 4 of us has put 2 payments on it.

**Comment by badcodestv** [comment]
How many are left at this time?

Would you mind providing the Plate and your CitizenID?

**Comment by Boundbyanxiety** [comment]
Place 7YJ868VC. CitizenID: HGF57349. according to the phone I have 7 payments left. If the other 3 people truly paid the 2 payments they each said they did, I should only have 2 more.

**Comment by Boundbyanxiety** [comment]
Im back in town.

**Comment by Boundbyanxiety** [comment]
Made another payment. Says i have 6 weeks left on it. So i should only have 1 payment left.

**Comment by Boundbyanxiety** [comment]
I just made What should be the last payment.

**Comment by theCitizen420** [comment]
For now, we recommend you ignore the payments as it will be handled following the inventory revamp. In the meantime, your car won't be repossessed. Any issues/questions, please reply here!

**Comment by katahtonic** [comment]
issue resolved db wipe, if the issue occurs again, reopen by commenting
