### ISSUE TITLE
[Bug] Taxi Meter registration

### ISSUE THREAD

**Issue by KatalysttTV** [FrenzyRoleplay/server-issues#161]
While driving on an NPC taxi job, The total job according to GPS on map was 5.6 miles. At the drop off point, the meter only read 4.9 miles and didn't register the last 3/4 of a mile on the rate. Not a big deal to me personally but just wanted to note it for you guys.

**Comment by badcodestv** [comment]
This shouldn't be happening any more to my knowledge since we've updated the taxi script.

**Comment by badcodestv** [comment]
If this continues, let us know and reopen up a ticket.
