### ISSUE TITLE
Hunting [Feature] 

### ISSUE THREAD

**Issue by SwampiePrincess** [FrenzyRoleplay/server-issues#165]
Possible Hunting Job

Hunting job that resembles the Fishing job

Hunt anywhere there is woods, but only from 4:30am to 5pm (like fishing).

i think it will add variety & could be fun!

**Comment by Cyntaax** [comment]
This was added with: https://github.com/FrenzyRoleplay/server/commit/7f4e220c046f8c8e198bbe5c174d9cb04c85600c
