### ISSUE TITLE
[Feature] Multicharacter

### ISSUE THREAD

**Issue by badcodestv** [FrenzyRoleplay/server-issues#17]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A UI revamp of the current multicharacter selector.

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/56496943/102719233-e51a7a00-42ba-11eb-9a9c-32a6095550d5.png)

**Comment by katahtonic** [comment]
merged in and released
