### ISSUE TITLE
Car Payment was taken out twice (Bug/Support Issue)

### ISSUE THREAD

**Issue by Reaper6six6** [FrenzyRoleplay/server-issues#172]
Went to pay on my Nightshade, but two payments were taken from my bank. Looks like only 1 week was knocked off the loan, but I saw 2 payment notifications, and 16,800 was taken from my bank instead of the 8400. 

ID at time of payment: 157 
Character Name: John Walker
Plate: 2NI325DZ

**Comment by katahtonic** [comment]
n/a
