### ISSUE TITLE
[Feature] Blue Bandana

### ISSUE THREAD

**Issue by SmokiinNugZz** [FrenzyRoleplay/server-issues#180]
ATM there isn't a blue paisley patterned bandanna like the bandannas other gang colors have. 
I know we still have other blue mask options, but it would be nice to have a blue bandanna similar looking to the image for inventory bandannas 

![mask blue and white](https://user-images.githubusercontent.com/78284338/107863927-c61a0d80-6e4f-11eb-9714-fad330aaf8fa.png)

**Comment by katahtonic** [comment]
should have sufficient colors now
