### ISSUE TITLE
Stuff poofing from inventory

### ISSUE THREAD

**Issue by noncanadianbear** [FrenzyRoleplay/server-issues#182]
While experiencing an issue where all my reactions would be delayed (which I have since hopefully fixed) certain things will disappear and reappear in my inventory when trying to move them. I was holding onto a stack of 400 og kush for a friend, and when I went to move it out of my trunk to my inventory, it looked like it worked. Just to double check, I stepped away and checked again, but the stack wasn't in my inventory anymore nor was it in my trunk.

I tried to rapidly swap between the two after fixing my delay issue, but the item is still gone, and I've even tried clicking empty spaces to see if it'll reappear.

Asked for help on the discord, was told best bet was to submit a ticket, not sure what else to try.

**Comment by katahtonic** [comment]
new inventory resolved
