### ISSUE TITLE
Hunting Issues

### ISSUE THREAD

**Issue by WTFJamie** [FrenzyRoleplay/server-issues#184]
**Describe the bug**
So after hunting there is no way to return the quad to get the deposit back, also on top of that once i was done hunting i still had the rifle roughly 15mins after killing the last deer.

i did a relog and upon waking up i still had the sniper rifle in my posession this was done nearly 25mins after the last deer was killed

**Expected behavior**
hunting rifle to be removed after the last deer is killed would be the best option.
also make hunting in the woods near the hunting grounds to limit the zone that way you could have it where there is no need for the quads and people can run around on foot and once they are done with hunting and leave the designated hunting area it would automatically remove the hunting rifle

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Cyntaax** [comment]
This was resolved by: https://github.com/FrenzyRoleplay/server-issues/issues/188
