### ISSUE TITLE
[Bug] Hunting

### ISSUE THREAD

**Issue by TaylorNel** [FrenzyRoleplay/server-issues#188]
**Describe the bug**
I did the hunting 2 times before this without any issue but when I did it this time, I got no meat when I slaughtered the deer. I checked and I had room in my inventory so that wasn't the problem. 

**Expected behavior**
To be able to slaughter the deer and get the meat

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Cyntaax** [comment]
This was resolved by https://github.com/FrenzyRoleplay/server/commit/e9605d9513e21dcd3e9f88823e38f7e98d5d05ad

**Comment by badcodestv** [comment]
Fixed on next restart
