### ISSUE TITLE
[Bug] Hunting timer may need fixed

### ISSUE THREAD

**Issue by Reaper6six6** [FrenzyRoleplay/server-issues#191]
**Describe the bug**
When starting to hunt, the timer send completely random. Sometimes you'll get 20+ minutes, and other times you'll get to the area and shoot 2 deer (maybe), and within that 5 minutes the timer expires. You lose out on the full deposit, and don't make enough back from selling too even break even.

**To Reproduce**
1. Seems to be a random issue, but affects multiple users. 

**Expected behavior**
There should be a set amount of time per hunt deposit. Maybe 30 minutes? But when you get the deposit back, the next hunt should start a new timer so you don't lose out on anything.

**Screenshots**

**Additional context**

**Comment by badcodestv** [comment]
Fixed on next restart.
