### ISSUE TITLE
my inventory cash is bug

### ISSUE THREAD

**Issue by hexpham92** [FrenzyRoleplay/server-issues#192]
when i notice my cash is scuff/bugs, i even try to go into the lights myself, and came back, my cash inventory is still bugs, now i try to send money to someone in person it would not let me, sometimes it wont even let me buy foods or anything
![glitch](https://user-images.githubusercontent.com/79233557/108285607-75f3c180-7155-11eb-8bcd-e0b89010f138.jpg)

**Comment by hexpham92** [comment]
btw this is huckleberry

**Comment by katahtonic** [comment]
issue resolved by wipe
