### ISSUE TITLE
House payment issue

### ISSUE THREAD

**Issue by PunisherInOKC** [FrenzyRoleplay/server-issues#196]
**Describe the bug**
Made a house payment of 31,500 on 2/13. The money was taken and the payment showed as complete. But today i see my house payment is 9 days overdue. The money spent on the house payment is gone.

**Comment by Nussifer** [comment]
That might have been the day they had to do a rollback to fix an issue, they put an announcement about it

**Comment by PunisherInOKC** [comment]
I looked back and do see that there was a rollback.  This rollback seems to have rolled back the house payment, but didnt rollback the funds in my bank.

**Comment by theCitizen420** [comment]
With the recent wipe, and the rollback that occurred, we'll be closing this. This should not be an issue moving forward. 

MARKED FOR CLOSURE.
