### ISSUE TITLE
Main Char was deleted somehow

### ISSUE THREAD

**Issue by DeviLzFury** [FrenzyRoleplay/server-issues#198]
**Describe the bug**
Went to make a new Char in slot 3.  Made new Char in slot 3 and saved.  Logged out of slot 3 char and wanted to get on main in slot one and that chars name was gone and not able to fly in as them.  Main Char who is missing is Jack Bass CID DFG82715 i think that his ID

**To Reproduce**
1. Go to 'Create new Char in slot'
2. Click on 'Create new char and make them'
3. Scroll down to 'Log out of new char and try to log into another already made char'

**Expected behavior**
Creating a new char should not delete one already made in another slot

**Screenshots**

**Additional context**

Clip that i did not by mistake delete main Char whne making new one

https://clips.twitch.tv/FriendlyMistyAsteriskSSSsss-nrvKFlSpCVINDUon

**Comment by katahtonic** [comment]
this was resolved in the DB, 2nd instance of it happening that I know of. seems to error during creation and just tosses id 1 on the new character with dummy names "Firstname Lastname" and empty birthdate
