### ISSUE TITLE
[Bug] trucker

### ISSUE THREAD

**Issue by Nussifer** [FrenzyRoleplay/server-issues#203]
**Describe the bug**
cant abort job says press X to abort but nothing happens......also pressing A on the controller is the X  key on the keyboard so you get the info any time you run

**To Reproduce**
1.  Hit X to cancel the job
2. doesn't cancel job

**Expected behavior**
Hit X and cancels job

**Screenshots**
![Screenshot_215](https://user-images.githubusercontent.com/69865982/108611196-6795e780-7399-11eb-922b-45bfe27bd637.png)

**Comment by cademullen** [comment]
This has been fixed.
