### ISSUE TITLE
Armor in mega mall [Bug] 

### ISSUE THREAD

**Issue by Sywel34** [FrenzyRoleplay/server-issues#210]
**Describe the bug**
the bug is basically every time you go to megamall to buy armor it says that there 50 in stock but when you buy let say like 5 or 10 the stock of 50 disappears and becomes 0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by yukisho** [comment]
This issue will be resolved in the Inventory Update. Also when items stock is at zero, someone needs to run the Delivery Job to replenish the stock.

**Comment by katahtonic** [comment]
issue resolved
