### ISSUE TITLE
Deliveries

### ISSUE THREAD

**Issue by Igerster** [FrenzyRoleplay/server-issues#211]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As a real estate agent, I can't do side jobs other than fishing, hunting.  I can't do the trucker, garbage, or other job.  Would it be possible to bring back the deliveries like we had in Frenzy 1.0?  The chicken, wood, dildo, and fleshlight deliveries were fun.  I would think that we could do that and keep our whitelist job since we go somewhere pick up the product, and deliver in our own vehicle.  It would give us something to do when we aren't selling houses, cars, etc. 

**Describe alternatives you've considered**

**Additional context**

**Comment by katahtonic** [comment]
issue resolved, added "2nd job" capability
