### ISSUE TITLE
[Feature] Adding Motorcycle Mechanic MLO in paleto bay

### ISSUE THREAD

**Issue by Grumpillar** [FrenzyRoleplay/server-issues#218]
**Is your feature request related to a problem? Please describe.**
this request is to solve the problem of not having a mechanic shop dedicated to fixing and restoring the motorcycles of los santos and would hopefully drive people up north and expand business in that area.

**Describe the solution you'd like**
i have found the MLO for this business and will include it below i would hope that this would allow for a biker centric repair shop for motorcycles

**Describe alternatives you've considered**
the majority of the mech shops foster a different type of rp atmosphere 

**Additional context**
[https://www.gta5-mods.com/maps/mlo-biker-mechanics-paleto-fivem-sp-ready](url)

**Comment by iChunkk** [comment]
@Grumpillar this would replace the recycling center at the moment.

**Comment by ProximateTv** [comment]
This can also be accomplished 100% in RP without a new MLO
