### ISSUE TITLE
[Bug] Auto Play on Phone Radio

### ISSUE THREAD

**Issue by badcodestv** [FrenzyRoleplay/server-issues#22]
**Describe the bug**
When listening to the music on the radio on the phone, it does not autoplay to the next song.

**To Reproduce**
1. Open up Phone
2. Click on the Radio App
3. Listen to a song all the way through
4. It doesn't go to the next song

**Expected behavior**
What should happen is that at the end of the current song, it should play the next song.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by katahtonic** [comment]
resolved
