### ISSUE TITLE
[Feature] Grim Reaper Cuts

### ISSUE THREAD

**Issue by Nussifer** [FrenzyRoleplay/server-issues#220]
Here are the Grim Reaper cuts I was told to add here I have both male and female cuts. The file isn't supported, so I uploaded it to a google Doc.

https://drive.google.com/drive/folders/1gv_JKjCer96tPcCmkiWJanVW7IcOzenk?usp=sharing

**Comment by ProximateTv** [comment]
I have pulled these and I will work on testing and resizing the textures

**Comment by ProximateTv** [comment]
This has been completed and can be closed once the items are tested on PTR/pushed to the live server.

**Comment by Reaper6six6** [comment]
Have these been tested on PTR as of yet? Not rushing, just checking on status.

**Comment by ProximateTv** [comment]
> Have these been tested on PTR as of yet? Not rushing, just checking on status. 

I've been in contact with Nussifer and Neko about this. Codes is checking in to why they aren't live when he is able
