### ISSUE TITLE
[Bug] SPAM E BUG IN FISHING

### ISSUE THREAD

**Issue by KELAMAN1** [FrenzyRoleplay/server-issues#228]
**Describe the bug**
BUG is when ur ping is high u spam in fishing it sells many time gives u cash cause of inventory loading time is slow.

**To Reproduce**
1. Go to 'the fishing'
2. Click on 'spam E'
3. sold for multiple time 

**Expected behavior**
only should sell once and all the fishes.

**Comment by goufbam** [comment]
Bump same issue now i have 500k

**Comment by ExoticMyth** [comment]
Same issue only i got 40K

**Comment by EmptyClipz** [comment]
Accidently did this but only double the $3900. So $7800 total

**Comment by WTFJamie** [comment]
just had this happen, made another 4.4k from it, it appears that slow pockets are a main factor in this issue aswel, with the system taking the fish but die to the pockets not registering the fish out of pockets, i would suggest the same kind of sell system as hunting to prevent this kind of issue

**Comment by katahtonic** [comment]
issue resolved
