### ISSUE TITLE
[Bug] Water doesn’t leave inventory after use

### ISSUE THREAD

**Issue by sg4bomb** [FrenzyRoleplay/server-issues#229]
When I drink water, it goes up on my water bar, but the bottle doesn’t get used in my inventory.

**To Reproduce**
1. Bought Water in a 2 stack from gas station by Grove St.
2. Drank water

**Expected behavior*
The water to go up on my bar and for it to leave my inventory.

**Screenshots**

**Additional context**

**Comment by katahtonic** [comment]
issue resolved
