### ISSUE TITLE
[Bug] Delivery driver job not paying

### ISSUE THREAD

**Issue by ajayWhit** [FrenzyRoleplay/server-issues#233]
Delivery driver job not paying.
Completed the delivery job all stores delivered to had the usual message to go get my payslip, when completed and pressed ‘E’ for my payslip it says no work had been done.

**To Reproduce**
1. Go to payslip after complete information delivery driver job. Press ‘E’
2. Click on 'get payslip’

**Expected behavior**
I expected to be paid my wage unsure of what the amount is due to the new wipe but was not paid a single dime.

**Screenshots**

**Additional context**

**Comment by theminotaurdad** [comment]
Just had the same issue, myself.

**Comment by cademullen** [comment]
This has been fixed
