### ISSUE TITLE
[Bug] Money duping while selling fish

### ISSUE THREAD

**Issue by ghosty93** [FrenzyRoleplay/server-issues#237]
**Describe the bug**
Basically, the fish after I was done fishing was stuck in my pockets for a while and I could sell them time and time again. It happened while the inventory was really laggy so it could be because of that

**To Reproduce**
1. Have a bunch of fish in pocket
2. Go to fish buyer dude
3. Spam the sell button on him

**Expected behavior**
It should only let you sell the fish once.

**Suggestion for a possible fix**
Maybe add like a 30 sec delay so that you can only sell your fish once every 30 sec to avoid the spam.

**Comment by ghosty93** [comment]
I want to add, I should have like ~10k in my pocket but when the server went down I had like ~50k from this

**Comment by katahtonic** [comment]
issue resolved
