### ISSUE TITLE
[Bug]  Pawn shop for laptops doesnt work

### ISSUE THREAD

**Issue by stubrud** [FrenzyRoleplay/server-issues#238]
**Describe the bug**
pawb shop where to sell phones,laptops etc is not there.

**To Reproduce**
1. Go to '.pawn shop'
2- its nothing there to interact to anymore

**Expected behavior**
a place to see that i coukd sell it or openingtime.

**Screenshots**

**Additional context**

**Comment by badcodestv** [comment]
This should be fixed. Closing.
