### ISSUE TITLE
[Bug] Resale of already sold fishes

### ISSUE THREAD

**Issue by AlexManila123** [FrenzyRoleplay/server-issues#239]
Resale of already sold fishes.

**To Reproduce**
Sell your fishes to the buyer and keep selling them over and over again.

**Expected behavior**
Make the amount of the sale over and over again.

**Screenshots**
Couldnt do it because i was kicked from the server
**Additional context**
I have 4 thousand dollars that i made while doing the trick.

**Comment by katahtonic** [comment]
issue has been resolved
