### ISSUE TITLE
[Bug] Prison Inventory

### ISSUE THREAD

**Issue by badcodestv** [FrenzyRoleplay/server-issues#24]
**Describe the bug**
When you get sent to prison, your items get taken away from you. Upon leaving prison after you've served your time, you get your items back. However, while you're still in prison and leave in the middle of your jail time & come back, you receive your items again and when leaving prison, you get your items back originally which is causing a dupe issue.

**To Reproduce**
1. Go to Prison with something in your pocket
2. F8 Quit or switch characters
3. Go back to the original character
4. You'll get spawned in back in prison
5. Check your pockets and you'll see that you'll have the same items as you went in with

**Expected behavior**
The removal of your inventory should happen once. When you fly back in while still being in jail, you shouldn't spawn in with your items that you went in with.

**Screenshots**
N/A

**Additional context**
Possible refactor of how being sent to prison works?

**Comment by katahtonic** [comment]
issue resolved?
