### ISSUE TITLE
Overpaid by PDM

### ISSUE THREAD

**Issue by theminotaurdad** [FrenzyRoleplay/server-issues#240]
Sorry if this is disorganized but I never saw a template for this. I sold my gold ticket car back to PDM and didn't realize until this morning that I had like 45K dollars in my account after buying the Bati801 I should have only had around 5 or 6k left in my bank. The sales notice said I was getting 17 something thousand.

**Comment by badcodestv** [comment]
This shouldve been reset with the second "post-wipe"
