### ISSUE TITLE
Phone doesn’t display text messages when opened 

### ISSUE THREAD

**Issue by Telly29** [FrenzyRoleplay/server-issues#241]
**Describe the bug**

When I pull out my phone my text messages appear but as soon as I go to open the message I get a black screen in the phone with no messages 

**To Reproduce**

[](https://gyazo.com/d18010d51fc528f35c4e0ee98bfd42ad) Go on your phone 
Click text messages 
Text messages open
Error of a black screen on phone nothing appears

**Expected behavior**

I expected my phone to open the text messages when I click to open so I can read what someone has messaged me.

**Screenshots**

https://gyazo.com/d18010d51fc528f35c4e0ee98bfd42ad

**Additional context**

I have cleared all of my caches files so I’m not sure what to try next I do have visual and la roads packs

**Comment by katahtonic** [comment]
resolved as of 3/4 please reopen if you continue to see an issue
