### ISSUE TITLE
[Bug] Physician Assistant isn't able to help up, also seeing a weird value when pulling out a vehicle from Pillbox.

### ISSUE THREAD

**Issue by Reaper6six6** [FrenzyRoleplay/server-issues#245]
**Describe the bug**
Physician Assistant is unable to use the Help Up and are not being counted as doctors on duty. Also, when trying to select a vehicle from pillbox, the vehicles are not listed properly. 

**Screenshots**
See attachment for vehicle issue
![218_20210301103813_1](https://user-images.githubusercontent.com/77019757/109520760-920f3100-7a7a-11eb-9c2c-cf5cd0140fc5.png)

**Additional context**

**Comment by badcodestv** [comment]
This has been fixed
