### ISSUE TITLE
[Bug] Items missing from trunk.

### ISSUE THREAD

**Issue by Reaper6six6** [FrenzyRoleplay/server-issues#246]
**Describe the bug**
I put my fish and fishing equipment in the trunk of my car, and when I got to the sell point, everything is gone. 

**To Reproduce**
Player ID at time: 69
Plate of car: 4JT424OX
Items lost: fishing pole, 150+ bait, 25+ fish

**Comment by laythdv** [comment]
I have nothing in the inventory showing that those items are in the trunk. I've tried to reproduce this many times in different vehicles with different items as well. Can't reproduce it.

**Comment by Reaper6six6** [comment]
I'm wondering if it didn't register the trunk and it just dropped them on the ground instead. I don't have a recording or anything, so I can't double check. Not a big deal, just wanted to make sure all was squared away with car/vehicle inventory.

**Comment by badcodestv** [comment]
Possibly? Just make sure when putting items over to the right side that its either glovebox, drop or trunk!
