### ISSUE TITLE
left Bumper opens inventory

### ISSUE THREAD

**Issue by Igerster** [FrenzyRoleplay/server-issues#247]
**Describe the bug**
Since 3.0 was released, hitting the left bumper on the controller also opens the inventory.  

**To Reproduce**
1. Press left bumper

**Expected behavior**
Not opening the inventory.  Left bumper also controls the rudder when flying. 

**Screenshots**

**Additional context**

**Comment by laythdv** [comment]
fixed on next restart

**Comment by badcodestv** [comment]
fixed on next restart
