### ISSUE TITLE
Jail Inventory[Bug] 

### ISSUE THREAD

**Issue by iChunkk** [FrenzyRoleplay/server-issues#248]
**Describe the bug**
when doing the electrical task in jail, you receive items, then when you do another task and receive that item, all other items in your pocket disappear.

**To Reproduce**
do electrical in jail

**Expected behavior**
items to remain in my pocket

**Comment by infusiontv** [comment]
same happen to me here a clip
 https://clips.twitch.tv/ConsiderateIcyClipsdadTwitchRPG--o9wuHQ1-zRQi04m

**Comment by laythdv** [comment]
I tried to reproduce this but was unable to. I searched multiple bins and did electrical work, but no problems.

**Comment by badcodestv** [comment]
I tried to reproduce this but was unable to. I searched multiple bins and did electrical work, but no problems.

**Comment by iChunkk** [comment]
> I tried to reproduce this but was unable to. I searched multiple bins and did electrical work, but no problems.

first job gave me a phone and steel. did another job, gave me rubber but my phone and steel were gone. 

also, got out of jail, and couldn’t claim any belongings.

**Comment by badcodestv** [comment]
Did you go to the corner and press E to retrieve items?

**Comment by iChunkk** [comment]
there was no prompt anywhere. me and spitts walked around the room spamming E.

**Comment by katahtonic** [comment]
issue should be resolved, please reopen if it occurs again
