### ISSUE TITLE
[Bug] jail not giving items back

### ISSUE THREAD

**Issue by Nussifer** [FrenzyRoleplay/server-issues#252]
**Describe the bug**
Went to jail for 10 months didn't get anything I had back from jail

**To Reproduce**
1. Go to jail takes all items
2. Release from jail get all items back

**Expected behavior**
Get release and get all items back from jail

![Screenshot_247](https://user-images.githubusercontent.com/69865982/109595892-83ecff00-7ad2-11eb-8e12-8578fff5c7a9.png)
![Screenshot_248](https://user-images.githubusercontent.com/69865982/109595895-83ecff00-7ad2-11eb-94bf-30ced74d892e.png)

**Comment by laythdv** [comment]
Yes. I never got a chance to update the message properly. There is a area out in the lobby to retrieve your jail items.

**Comment by badcodestv** [comment]
Yes. I never got a chance to update the message properly. There is a area out in the lobby to retrieve your jail items.

**Comment by Nussifer** [comment]
ya a trooper found it. It's in a crazy spot he said he talk to the high command about moving it.
