### ISSUE TITLE
[Bug] Deer Meat Weightless

### ISSUE THREAD

**Issue by Trauma-Llama** [FrenzyRoleplay/server-issues#254]
**Describe the bug**
Went hunting expecting to do one trip then have to sell but deer meat is weightless
**To Reproduce**
1. Go on hunting trip
2. get meat
3. notice no weight
4. People could spend hour after hour hunting and stack up on it and sell in bulk

**Expected behavior**
too only be able to do one trip due to weight constraints

**Screenshots**
![FiveM_b2060_GTAProcess_eqde1Z3PL6](https://user-images.githubusercontent.com/78266337/109676805-4a4ddf80-7b36-11eb-9095-2ddd10c7dfb6.png)

**Additional context**

**Comment by badcodestv** [comment]
Fixed on next restart
