### ISSUE TITLE
[Bug] Inventory can't move items

### ISSUE THREAD

**Issue by Trauma-Llama** [FrenzyRoleplay/server-issues#255]
**Describe the bug**
Not sure what is causing it, But I keep running into an issue with the inventory where a single left click will switch the items inventory  IE Pockets->Ground, Pockets>Glovebox. This makes it so i can't rearrange my inventory or use anything as i can't drag items to the USE bar and can't move items onto my hotbar/quickbar

**To Reproduce**
Honestly, I have no idea how to reproduce, I haven't been able to pinpoint it.. Could be from accidently double clicking inventory (TAB). Will update this if I figure out more with it.

**Expected behavior**
that the inventory would constantly allow me to move and rearrange items and not instantly switch inventories

**Screenshots**

**Additional context**
Sorry for the lack of info, It has happened 3 times and I don't know why.

**Comment by katahtonic** [comment]
this is likely caused by a keybind issue, the new inventory only opens once with tab and tab again will not affect the open state. not able to replicate
