### ISSUE TITLE
[Bug] Coral not saving to inventory/pockets

### ISSUE THREAD

**Issue by BigSmashGG** [FrenzyRoleplay/server-issues#260]
**Describe the bug**
 Coral doesn't work

**To Reproduce**
Get to the Diving area on the map. Deep dive down and collect coral. The coral is not saving itself to the inventory/pockets of the charachter. 

**Expected behavior**
I expect the coral to be in the pocket/inventory of the character so i can sell it off at the store.

**Screenshots**
No screenshots were taken

**Additional context**
When diving down to the coral area, mark would appear to collect coral, however when collection finished the coral was not in the pockets

**Comment by katahtonic** [comment]
you now pick up coral correctly
