### ISSUE TITLE
Same In Game Phone Number As another player

### ISSUE THREAD

**Issue by mattleon97** [FrenzyRoleplay/server-issues#265]
**Describe the bug**
While in city, I got a call from a random player on the server and I didn't know him whatsoever. I then could see all of his sent and received text messages and kept receiving messages and calls from his friends.

**To Reproduce**
I'm not sure if it's reproducible, I just started having this happen.

**Expected [behavior**]
I just keep getting texts and calls from players that this other person is friends with.

**Screenshots**

![image](https://user-images.githubusercontent.com/79957392/109752561-7a789b00-7b95-11eb-9738-a39d852234fb.png)
![image](https://user-images.githubusercontent.com/79957392/109752584-85333000-7b95-11eb-850d-1b79645210cb.png)
1st image is the list of messages from other people I don't know
2nd image is me telling the player it's not me.
**Additional context**

**Comment by katahtonic** [comment]
is this still an issue, and what's your phone number, if so

**Comment by mattleon97** [comment]
It’s not an issue anymore, I had to remake my character back towards the
beginning of the wipe.
