### ISSUE TITLE
Pockets clearing in prison after doing jobs [Bug] 

### ISSUE THREAD

**Issue by Kazuhira925** [FrenzyRoleplay/server-issues#266]
**Describe the bug**
While doing jobs in prison items will disappear from the inventory when doing another job. For instance if you do one job and get 3 rubber, then do another job and get 3 joints, your rubber will be gone but you'll have the joints.

**To Reproduce**
1. Go to Prison
2. Click on the stove prison job or the trash can searching (I believe even the prison crafting bench will wipe the pockets)
3. Scroll down to just wait.
4. Pay attention to your inventory before and after doing one of the prison jobs

**Expected behavior**
Your pockets essentially reset after every time you interact with anything in the prison kitchen (idk if there are prison jobs elsewhere these are the only ones I know about)

**Screenshots**
Did not get screenshots at the time I will if I end up in prison again.

**Additional context**
I did keep what I had in my pockets when I was released from prison, was about 3 rubber.

**Comment by katahtonic** [comment]
issue was resolved, please submit another bug report or reopen this one if there is still an issue
