### ISSUE TITLE
[Feature] Inventory (WIP)

### ISSUE THREAD

**Issue by badcodestv** [FrenzyRoleplay/server-issues#27]
**Is your feature request related to a problem? Please describe.**
Current inventory is very buggy. Players lose items from their stashes such as homes, apartments, gloveboxes and trunks. Current inventory is also lacking item decay.

**Describe the solution you'd like**
New inventory should not have any loss of player items. New inventory should also have item decay.

**Describe alternatives you've considered**
N/A

**Additional context**
![decay](https://user-images.githubusercontent.com/56496943/102855747-3168d580-43f3-11eb-88cd-40bb5396923f.png)

**Comment by katahtonic** [comment]
new inventory released! :D
