### ISSUE TITLE
[Bug] Can't Sell Coral

### ISSUE THREAD

**Issue by Trauma-Llama** [FrenzyRoleplay/server-issues#271]
**Describe the bug**
Stopped off at a diving site and got some coral. Went to the shop on the pier to sell the coral. Got no money "you do not have any coral to sell" (or something along those lines) and the option to sell now is gone. 

**To Reproduce**
1.Collect coral (The coral I had was Antipatharia Coral)
2. Head to the shop on the pier to sell the coral
3. Says you have no coral and doesn't take the coral from you
4. The option to sell the coral with "g" is now gone.

**Expected behavior**
Too be able to sell the coral I collected.

**Screenshots**

**Additional context**
After writing this I drove a bit down the pier drove back and the option to sell came up again. Same result

**Comment by WTFJamie** [comment]
can confirm this was unable to sell any coral that i had collected.


![FiveM_b2060_GTAProcess_JEswCYCkSF](https://user-images.githubusercontent.com/78179708/109887313-5f7f5700-7c79-11eb-864f-a21086560e59.png)

![FiveM_b2060_GTAProcess_7yJm70NA9N](https://user-images.githubusercontent.com/78179708/109887315-61e1b100-7c79-11eb-91f3-dd8ac59c4c16.png)

**Comment by katahtonic** [comment]
fixed
