### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Nesproc** [FrenzyRoleplay/server-issues#273]
**Describe the bug**
During the delivery job if you use a watch and then try to pick up a package it stops you from ever picking up the package again unless you f8 quit

**To Reproduce**
1. Get delivery job and go to a drop
2. put on a watch in the back of the truck
3. while the watch is getting put on try to pick up a package
4. See error <---

**Expected behavior**
the ability to pick up the package once the watch is on

**Screenshots**

**Additional context**

**Comment by katahtonic** [comment]
fixed
