### ISSUE TITLE
Scuffed ammunation [Bug] 

### ISSUE THREAD

**Issue by Kazuhira925** [FrenzyRoleplay/server-issues#275]
**Describe the bug**
The Ammunation in Sandy Shores is scuffed and shows at least 7 different "E - Shop" markers throughout the store, most of them being behind the walls.

**To Reproduce**
1. Go to Ammunation in Sandy Shores
2. Click on nothing
3. Scroll down to nothing
4. See multiple "E - Shop" prompts

**Expected behavior**
When you walk into the store you will immediately see multiple shop markers.

**Screenshots**
https://i.gyazo.com/e1a0909444194e24aeb3b804441dc670.jpg

**Additional context**

**Comment by yukisho** [comment]
Unable to reproduce this.

https://i.imgur.com/XGic4Ii.png

**Comment by katahtonic** [comment]
please reopen if you still have this issue and we can try to look further into it. not reproducible
