### ISSUE TITLE
[Bug]Coral not selling

### ISSUE THREAD

**Issue by BigSmashGG** [FrenzyRoleplay/server-issues#277]
**Describe the bug**
Went to sell the coral and after it was done "receiving" the coral I received a notification that I had no coral to sell. 
The coral remained in the inventory/pockets
The "sell coral" prompt disappeared from the store to sell it at also, even though the coral was on inventory to sell

**To Reproduce**
1. Goto Coral selling store
2. Sell Coral
3. Receive error

**Expected behavior**
Sell the collected coral off and collect money

**Comment by katahtonic** [comment]
fixed
