### ISSUE TITLE
[Bug] Helicopter Repelling

### ISSUE THREAD

**Issue by HendiakaMeow** [FrenzyRoleplay/server-issues#28]
**Is your feature request related to a problem? Please describe.**
Repelling does currently "work" so it just needs to be fixed

**Describe the solution you'd like**
Make Repelling function more smooth so it can be utilized in RP

**Describe alternatives you've considered**
We tried using it with different timing but its not reliable enough to trust.

**Additional context**
It seems like the animation isnt working properly, and when the person on the rope reaches the bottom they get stuck in a ragdoll.

**Comment by badcodestv** [comment]
This is also the same script with the spotlight too so I'll see what we can do about fixing this issue.

**Comment by badcodestv** [comment]
This is fixed for the next restart!
