### ISSUE TITLE
[Bug] House robbery items...

### ISSUE THREAD

**Issue by Nussifer** [FrenzyRoleplay/server-issues#293]
**Describe the bug**
items that are taken from house robberies are showing the person who got them citizens ID......instead of them being blurred out

**To Reproduce**
1.  rob a house
2.  get a gun or anything from the house 
3.  shows your citizen ID 

**Expected behavior**
the items should show you blurred citizens ID

**Screenshots**

![20210306034408_1](https://user-images.githubusercontent.com/69865982/110205803-6227ab00-7e37-11eb-8cb2-ee7d51bea62c.jpg)

**Comment by badcodestv** [comment]
This has been patched in recent updates.
