### ISSUE TITLE
[Bug] MDT error when submitting report

### ISSUE THREAD

**Issue by DeltaMercenary** [FrenzyRoleplay/server-issues#30]
When I fill out a report for a cold case file in MDT it is turning into a white screen with an error, and I am unable to use MDT again without flying out and back in.  I have included a screen shot of the error.

I have had this happen twice in a row when trying to make a cold case file to attach evidence to.  I fill out all the blanks in the report except for the report number, and I did not select any charges as this is a cold case file currently.

[https://imgur.com/N3W0s7b](url)

**Comment by badcodestv** [comment]
@yukisho Mind looking into this?

**Comment by yukisho** [comment]
When submitting this report, are you going to the Cold Case profile and clicking the green New Report button or are you clicking on Create Report in the rop right of the page?

**Comment by DeltaMercenary** [comment]
This is happening either way I try to put in a new report, I tried to click the create report button for a new case last night and once I filled out everything and clicked submit I got the same error and It stays like that until I take a flight. Last night it happened on the create report on the top right for sure.

**Comment by yukisho** [comment]
Thank you, I will look into it and update this when a solution has been implemented.

**Comment by badcodestv** [comment]
Solution has been implemented.
