### ISSUE TITLE
[Bug] Multiple E- Shop Locations from AmmuNation

### ISSUE THREAD

**Issue by theCitizen420** [FrenzyRoleplay/server-issues#303]
**Describe the bug**
When you go to AmmuNation in Little Seoul (next to Weazel News), you can see prompts for E - Shop for what seems like "all" AmmuNations in the distance.

**To Reproduce**
1. Go to AmmuNation in Little Seoul.
2. See E- Shop show up multiple places. 

**Expected behavior**
Only see the E - Shop for the store I am in. 

**Screenshots**
Screenshot attached. 
![shop at ammunation](https://user-images.githubusercontent.com/76059658/110324884-95f40380-7fe4-11eb-8329-0f31eb75a4f9.JPG)

**Comment by cademullen** [comment]
This should be resolved
