### ISSUE TITLE
Every car I got into was stalling... believe it is related to the condition of my personal car...

### ISSUE THREAD

**Issue by Nesproc** [FrenzyRoleplay/server-issues#308]
**Describe the bug**
Every car I got into was stalling... believe it is related to the condition of my personal car...i crashed my car and every vehicle i used would stall out... when i got my personal car back it was doing the same thing until i got it repaired....(not 100% repeatable but i did quit and and come back)

**To Reproduce**
1. wreck car(i think it was transmission)
2. steal new car 
3. car stalls every 10-30 seconds

**Expected behavior**
Condition of personal vehicles should not be tied to all cars

**Screenshots**

**Additional context**

**Comment by katahtonic** [comment]
fixed
