### ISSUE TITLE
[Bug] Explot @ Bean Machine

### ISSUE THREAD

**Issue by Runix317** [FrenzyRoleplay/server-issues#309]
**Describe the bug**

**To Reproduce**
1. Go to 'Bean Machine'
2. Click on 'Pack orders while one person stands near register "pink shirt" pink shirt grabs order looks to left and can cancel order and complete the process over and over while the other person gets money for doing so nonstop.'

**Expected behavior**

**Screenshots**
https://clips.twitch.tv/SmallBlushingFennelJKanStyle-6k4jUwwZgIwTPTN8

**Additional context**
any questions discord is NotSeth#2404

**Comment by katahtonic** [comment]
fixed (removed)
