### ISSUE TITLE
weight in stashes and trunks are bugged

### ISSUE THREAD

**Issue by Axcii** [FrenzyRoleplay/server-issues#311]
**Describe the bug**
when pulling items from stashes or trunks, you can put however much weight in your pocket that you want. it doesn't update as you add, only when you close your pocket and open it back up.
same with trunks. you can put however much weight you want in the trunk, it doesn't update the weight as you add, only when you close the trunk and open it back up.
hard to explain

![Screenshot_2](https://user-images.githubusercontent.com/75816765/110536190-ca4fe880-80e6-11eb-959a-3e0a1c1b56e0.png)

**Comment by katahtonic** [comment]
should be fixed, please reopen if it happens again

**Comment by Axcii** [comment]
appreciate you kat!
