### ISSUE TITLE
[Bug] Beach Closed But Can Still Metal Detect.

### ISSUE THREAD

**Issue by ExoticMyth** [FrenzyRoleplay/server-issues#315]
**Describe the bug**
Beach closes and you can still metal detect

**To Reproduce**
1. Have the metal detector out when the time ends
2. you will still be able to metal detect until you put it away. 
**Expected behavior**
It should stop you and make you put it away.

**Screenshots**

**Additional context**

**Comment by katahtonic** [comment]
fixed
