### ISSUE TITLE
Ammo Not Saving[Bug] 

### ISSUE THREAD

**Issue by WTFJamie** [FrenzyRoleplay/server-issues#318]
**Describe the bug**
everytime i have fully loaded a gun and left the server and come back my ammo count has been back at 0, so it seems that ammo is not saving

**To Reproduce**
1. load ammo
2. leave sever
3. rejoin server

**Expected behavior**
ammo to be saved after leaving the server aswel as after restarts

**Comment by Nussifer** [comment]
I don't have this issue

**Comment by WTFJamie** [comment]
yeah i dont know whats going on the last 2 days ive had no ammo in my gun when waking up not seeing anything in f8 either

**Comment by badcodestv** [comment]
This should've been fixed in previous updates.
