### ISSUE TITLE
[Bug] Serial Numbers not showing for Evidence

### ISSUE THREAD

**Issue by JinxLiam** [FrenzyRoleplay/server-issues#325]
**Describe the bug**
When a police officer attempts to collect a bullet casing, we cannot see the serial number of the bullet

**To Reproduce**
1. Use your flashlight to see bullet casings on the ground
2. Collect a bullet casing by pressing G

**Expected behavior**
Police Officers should be able to see the serial number on evidence bags

**Screenshots**
https://i.imgur.com/uiX1al3.jpg
https://i.imgur.com/BqBsQu9.jpg
https://imgur.com/a/gBJAbBp

**Comment by badcodestv** [comment]
This has been fixed in previous patches.
