### ISSUE TITLE
Lotto tickets not disappearing after loss [Bug] 

### ISSUE THREAD

**Issue by Kazuhira925** [FrenzyRoleplay/server-issues#329]
**Describe the bug**
Lottery tickets are not disappearing after a failed scratch, you get the failed prompt but the ticket stays until you win. They disappear when you do win however.

**To Reproduce**
1. Go to anywhere lotto tickets are sold.
2. Click on the tickets and buy any amount.
3. Scroll down to nowhere.

**Expected behavior**
The lottery tickets will stay in the inventory even if the user loses, they only disappear once the user wins.

**Screenshots**
Nothing to screenshot.

**Additional context**
A few of us had purchased lotto tickets and didn't notice they were bugged right away, we've let people know not to purchase anymore at the moment.

**Comment by hhenry12** [comment]
I would like to provide a video to this since I just came across this bug https://streamable.com/ngf6pc

**Comment by katahtonic** [comment]
fixed
