### ISSUE TITLE
[Bug] CORAL not Selling

### ISSUE THREAD

**Issue by sirknoe** [FrenzyRoleplay/server-issues#332]
Coral when harvested is added to your pockets, however, when going to sell the Coral via the sell at the store on the Pier you press G it loads and at the end it does not take the coral or give you cash and gives you a prompt saying you do not have coral to sell when you do. 

I also would like to add is the Coral spots are somewhat quick to finish you harvest a few spots and it moves across the island. It is frustrating to do I feel if the payout is balanced to accommodate travel time and diving etc it may even out the desire to only do one whitelisted job.

Thanks everyone!

**Comment by katahtonic** [comment]
resolved please reopen if you still have a problem
