### ISSUE TITLE
[Bug] ammo disappearing after storing/swapping/relogging

CID: CNA10472
everytime as i fly in or switch guns the ammo keeps dissapearing

### ISSUE THREAD

**Issue by Tattguynick** [FrenzyRoleplay/server-issues#337]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Reaper6six6** [comment]
I have this same issue on all characters. I will log out with well over 100 rds, and then when I log in the next day, all of my ammo is gone.

**Comment by badcodestv** [comment]
This has been fixed in previous patches.
