### ISSUE TITLE
[Bug] Ammo

### ISSUE THREAD

**Issue by Miliax** [FrenzyRoleplay/server-issues#341]
**Describe the bug**
Everytime you relog on your character you lose the ammo you had in your gun and you need to reload it with new ammo. Same if you buy a new gun even if u had ammo in the recent gun, the new gun will be empty.

**To Reproduce**
1. Buy a gun
2. Put in ammo in the gun
3. Relog
4. And your gun will be empty.

**Expected behavior**
That the ammo will stay even if you relog.

**Screenshots**
![image](https://user-images.githubusercontent.com/51051445/111051529-04f1b200-8454-11eb-959e-c44345603d8f.png)

**Additional context**
Video : https://youtu.be/ChROp9zT4Tg
Citizen ID: XJO77641

**Comment by Boundbyanxiety** [comment]
I second this. I bought a gun last night. Bought a bunch of ammo for it. When i flew in this morning it had no ammo. Citizen ID: PCP79332

**Comment by brookie41** [comment]
Same issue here. Third time I flew in and my gun is cleared of ammo.

**Comment by badcodestv** [comment]
This should be fixed in the previous patches of ammo fixes. Please re-open if you experience this issue.
