### ISSUE TITLE
[Bug] House robbery issue

### ISSUE THREAD

**Issue by Miliax** [FrenzyRoleplay/server-issues#342]
**Describe the bug**
When you do house robberies you can get scuffed and not be able to continue searching. For example: I drank a Madrinas and before i was done drinking i pressed H to search by accident and it said '' you working on something else '' and when i was done drinking i couldn't continue searching. 

**To Reproduce**
1. Do a houserobbery
2. Use something in your inventory such as food, madrinas etc.
3. Before you are done with the action, Press H to search something in the house
4. When you are done with the action, try press H to search and it wont work.

**Expected behavior**
To be able to continue searching the house even though you accidentely pressed H before you done drinking etc. 

**Screenshots**
No screenshots

**Additional context**

**Comment by badcodestv** [comment]
This was fixed in a previous patch if I remember correctly. Same thing occurred when drinking/eating during a truck delivery. Reopen if you still experience issues.
