### ISSUE TITLE
[Bug] Lotto Tickets

### ISSUE THREAD

**Issue by LonelySkullKid** [FrenzyRoleplay/server-issues#359]
**Describe the bug**
when you purchase a lotto ticket and you lose "better luck next time" it doesn't disappear from your inventory it stays there till you get a winner
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'lotto tickets any shop'
2 just buy 1 and put it in a quick slot'
3. keep using same ticket till you get a win

**Expected behavior**
a loss means ticket is a dud and disappears

**Comment by badcodestv** [comment]
This should be fixed in recent patches.
