### ISSUE TITLE
[Bug] Missing ammo when logging in. 

### ISSUE THREAD

**Issue by Reaper6six6** [FrenzyRoleplay/server-issues#361]
**Describe the bug**
Every time I spawn in, all of my ammo that was last loaded is gone. 

**To Reproduce**
1. Load up gun.
2. Log out
3. Log back in
4. pull gun, be sad from no ammo.

**Expected behavior**
Ammo should stay as long as the gun is not broken.

**Comment by badcodestv** [comment]
This should be fixed in per recent patches. If it continues to happen, please re-submit at ticket.
