### ISSUE TITLE
[Bug] Hello, I'm Rico Suave from esb. I've been having issues with tattoos, I have to put them on every time I relog because they disappear when I log off.

### ISSUE THREAD

**Issue by RichieTheGoat** [FrenzyRoleplay/server-issues#367]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by badcodestv** [comment]
Is this still happening?

**Comment by katahtonic** [comment]
@RichieTheGoat Please provide your player citizen ID (that had the problem with tattoos) when you can. the issue should be resolved, but I want to check something in the DB
