### ISSUE TITLE
[Bug] Loss of items, items converting to other things

### ISSUE THREAD

**Issue by Reaper6six6** [FrenzyRoleplay/server-issues#371]
**Describe the bug**
Had an issue where I put my phone and radio in my glovebox. W\hen I went to swap them back, my radio disappeared, and my phone turned into bait. 

**To Reproduce**
1. Seems to happen randomly, but the issues are becoming excessive with the new inventory. 

**Expected behavior**
Items should not change or disappear.

**Comment by katahtonic** [comment]
they aren't disappearing they were stacking with other items. break apart the stacks and close/reopen  your inventory/stash and it will show the right items. this bug has been fixed and should not happen in the future
