### ISSUE TITLE
CryptoLaptop[Bug] 

### ISSUE THREAD

**Issue by Schoeni123** [FrenzyRoleplay/server-issues#380]
**Describe the bug**
If you go down to the port near the Buckstar-Depot, you can use a Laptop which says :"Press E. What is this? (20 Emblems)".
If 20 Emblems are collected and E is pressed, in the right upper corner the message "network unavaible". I asked arround and another 2 people tried the same thing and had the exact same problem. I figured maybe there is a specific timeframe for that, but one player who I talked to, told me the that it normaly works every time. 

**Expected behavior**
Normally there should be a timestamp and a marker on the map which shows when and where, someone can rob a gasstation.

**Comment by badcodestv** [comment]
The network unavailable is something you can find out in RP, however it is not broken at this time.
