### ISSUE TITLE
[Bug] Evidence Bags

### ISSUE THREAD

**Issue by Fr0stedM0nster** [FrenzyRoleplay/server-issues#383]
**Describe the bug*

When you go to collect any blood with an evidence bag it puts the evidence bag in your pocket and removes it at the same time

**To Reproduce**
Find a blood sample with a flashlight well having an empty evidence bag and try to collect the sample

**Expected behavior**
When a blood sample is taken at a crime scene well using a flashlight it’s supposed to remove one empty evidence bag and put one filled evidence bag in your inventory with the samples DNA code to reference it in the mdt.

**Screenshots**

**Additional context**

**Comment by badcodestv** [comment]
Fixed on next restart
