### ISSUE TITLE
Waking up/entering houses [Bug] 

### ISSUE THREAD

**Issue by Nekomeowancer** [FrenzyRoleplay/server-issues#39]
**Describe the bug**
The last few days I've been having constant issues flying into my properties no matter where on the city map, I cannot seem to load past the loading in black screen, sometimes sitting there for 10mins before it even allows me to see an interior. Sometimes even if I wake up at the bus station and attempt to enter a property that way it's the same issue. Cleared my cache, removed all graphic mods added onto FiveM and even have rolled back my graphics driver to see if this will help and still the same issue.

**To Reproduce**
1. Selected character
2. Selected choice wake up destination, generally West Eclipse Blvd Property and waited for /enter to appear before clicking confirm
3. sits in loading black screen for 10 mins
4.  Never load in and have to F8 quit and try again, usually waking up at integrity bus station

**Expected behavior**
1. Selected character
2. Selected choice wake up destination, generally West Eclipse Blvd Property and waited for /enter to appear before clicking confirm
3. Wake up inside interior with no issues

**Screenshots**
https://i.imgur.com/R26pkqs.jpg
https://i.imgur.com/yaihncC.jpg

**Additional context**
This has been an on going issue since the 23rd of December for me, even uninstalling FiveM, GTA and reinstalling them has not worked.

**Comment by katahtonic** [comment]
this appears to be an issue with the max client set to 75. she was able to sign in after connecting to my local machine. 
@Nekomeowancer , let me know if you have further issues now that we're back to a 64 cap

**Comment by katahtonic** [comment]
issue resolved
