### ISSUE TITLE
[Bug] Health saved with outfit

### ISSUE THREAD

**Issue by Miliax** [FrenzyRoleplay/server-issues#390]
**Describe the bug**
Everytime i log in, a little bit of my health is gone. I've been wondering why and i figured out why. Your health is saved with the outfit that you are saving. So if you don't have full health and you save it, you'll wake up with that everytime and if you change to that outfit when you have 100% health it will give u the health u had when you saved the outfit.

**To Reproduce**
1. Create 2 outfits, one with 100% health and one with less health.
2. Save both outfits. 
3. Now swap between the 2 outfits you made.
4. You'll see that the health bar changes everytime. 

**Expected behavior**
To not save the health with the outfit.

**Screenshots**
I have a video :)
https://youtu.be/nbasY0wZpr0

**Additional context**

**Comment by Miliax** [comment]
I don't even know if it has to do with the outfits anymore. I wake up with less health all the time even tho i have a outfit that i saved with full health...

**Comment by badcodestv** [comment]
Outfit 1
![image](https://user-images.githubusercontent.com/56496943/113765630-856da080-96ea-11eb-9c5b-33c7139acb4b.png)

Outfit 2
![image](https://user-images.githubusercontent.com/56496943/113765676-96b6ad00-96ea-11eb-86c2-bd017a32cc27.png)


Also fixed where if you made a new character or spawned in, you'll be at full health too (unless ur dead of course). This will be fixed next restart.
