### ISSUE TITLE
[Bug] Bean Machine delivery driver rep not increasing.

### ISSUE THREAD

**Issue by Kazuhira925** [FrenzyRoleplay/server-issues#397]
**Describe the bug**
Bean Machine drivers are saying that their delivery rep is not increasing when they are doing food runs with bands, (I myself haven no idea how this system works as I have never fully gotten into it) But I have had multiple people tell me that their rep is supposed to increase after a certain amount of runs with bands, however it isn't increasing for anyone. (Have tried with and without bands and still the same result)

**To Reproduce**
1. Go to Bean Machine with bands.
2. Click on "pickup a delivery"
3. Scroll down to N/A
4. Check f8 after deliveries and see if rep increases

**Expected behavior**
From what people have told me rep is supposed to increase after a certain amount of runs with bands.

**Screenshots**
Don't have any screenshots.

**Additional context**

**Comment by laythdv** [comment]
This is working as intended.

**Comment by badcodestv** [comment]
This is working as intended. With the wipe, we did decrease the amount of time to get your rep up so that it was more of a slow grind.
