### ISSUE TITLE
[Bug] Percocet Broken still useable

### ISSUE THREAD

**Issue by Trauma-Llama** [FrenzyRoleplay/server-issues#398]
**Describe the bug**
Percocets can still be used after breaking.

**To Reproduce**
Have a broken percocet
Use it
Still works fine

**Expected behavior**
It till tell me it's broken or moldy or something and unable to use,

**Screenshots**

**Additional context**

**Comment by badcodestv** [comment]
I'm unable to repro this. Have you been able to repro this again?

**Comment by Trauma-Llama** [comment]
Haven't used percocets Since all mine "broke" So I dropped them, and haven't bothered to get more. But if you can't reproduce could have been fixed in the past 9 days?

**Comment by badcodestv** [comment]
Probably

**Comment by Trauma-Llama** [comment]
Close? If I notice it in the future i'll bring it up again.
