### ISSUE TITLE
Misty Rose (warymermaid7519) was on a water rescue when she went down. Her ems system shut off and she had to manually type in 911. When she got back to pillbox it showed she was still on duty

### ISSUE THREAD

**Issue by WaryMermaid** [FrenzyRoleplay/server-issues#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Cyntaax** [comment]
Can you fill the form out properly? Placing the entirety of your issue in the title makes it difficult to read.
