### ISSUE TITLE
[Bug] drink water after drunk

### ISSUE THREAD

**Issue by Nussifer** [FrenzyRoleplay/server-issues#402]
**Describe the bug**
after drink 3 bottles of water still drunk

**To Reproduce**
1. drink 3 alcohol 
2.  drink 3 bottles of water
3.  still drunk
**Expected behavior**
after drinking 3 drinks of water sober up 

did it in front of EMS Jessica Jones  discord name Nekomeowancer

**Comment by badcodestv** [comment]
Fixed on next update.
