### ISSUE TITLE
[Bug] Job Menu Not Switching w/ Character Change

### ISSUE THREAD

**Issue by brookie41** [FrenzyRoleplay/server-issues#41]
**Describe the bug**
Similar to the radio still staying on encrypted channels while logging out to another character, the F1 job menu is getting messed up as well. I logged out of Ariel Rose (judge) via the bed in the apartment and onto Kylie Decker (LEO). I clocked on duty as cop and am able to see all the blips, talk on the radio channel, and can do my job duties via /words; but under F1 wheel the police section isn't there. 

**To Reproduce**
1. Go to a different character possibly with another whitelisted job, log out via the apartment instead of taking a full flight.
2. Go on cop character and clock in.
3. Press F1.
4. See that the police section on the F1 wheel is not there.

**Expected behavior**
When clocking on as PD, it would be expected to see the Police job menu under the F1 options wheel.

**Screenshots**
https://imgur.com/ocwJYaG

**Additional context**
N/A

**Comment by brookie41** [comment]
was able to get the job menu back by clocking out and back in

**Comment by katahtonic** [comment]
issue resolved
