### ISSUE TITLE
[Bug] Double Cheeseburger not removing from inventory

### ISSUE THREAD

**Issue by BigSmashGG** [FrenzyRoleplay/server-issues#410]
**Describe the bug**
When i goto use a Double Cheeseburger, it is not removing itself from inventory

**To Reproduce**
1. Move food over to use
2. I eat one
3. Double Cheeseburger is still in inventory

**Expected behavior**
remove the double cheeseburger

**Comment by cademullen** [comment]
This has been fixed.
