### ISSUE TITLE
[Bug] Jail/Gate Locks

### ISSUE THREAD

**Issue by mehoygg** [FrenzyRoleplay/server-issues#411]
**Describe the bug**
In the visitation center, the door/gate locks inside and leading to the visitation center, also double for the vehicle gates.  One opens the other etc.  or the locks can be flipped as in if you unlock one the other lock locks and vice versa. 

**To Reproduce**
1. Go to 'visitation at the prison and look to the left.
2. Click on 'E to lock/unlock'

**Expected behavior**
The Locks should not reach one another. 

**Screenshots**
https://imgur.com/a/q6VkUC5

**Additional context**

**Comment by badcodestv** [comment]
With the new prison coming in, we can fix this problem. For now, I'll close this out until then.
