### ISSUE TITLE
Bike stand at tuner 

### ISSUE THREAD

**Issue by Nekomeowancer** [FrenzyRoleplay/server-issues#416]
It's becoming an issue especially with the lower bikes (zombies, avarus, nightblade) that we can not repair the bikes without having to prop them up on a trolley, stairs or the seat down back. It looks unrealistic and unprofessional for the customers when we repair the bikes and sometimes we can't even find the checkstatus spot

A bike ramp like they have at 68 and smoking axle for us at tuner would be amazing.

Maybe a fix on the low rider bikes so we can repair them from the handlebars.

**Comment by nixety** [comment]
This request has already been asked. As its brought to my attention I shall be visiting tuner shop to see what improvements I can perform.

**Comment by Nekomeowancer** [comment]
Appreciate it Nixety
