### ISSUE TITLE
[Bug] Phone number linked to other numbers

### ISSUE THREAD

**Issue by AshlynTV** [FrenzyRoleplay/server-issues#422]
**Describe the bug**
Some people have the same number as others in the city. They are linking together and messages are being seen from other people's phones in the city.  I'm not the only person having this issue.

Not to exspect
Not have numbers linked when creatign character

**Screenshots**
Fivem is down, cant get it.

*

**Comment by laythdv** [comment]
Should be fixed on next update. If you or someone you know has duplicate phone numbers, please have them open up a support ticket with their CitizenID attached to the ticket so we can fix the phone numbers for them.

**Comment by badcodestv** [comment]
Should be fixed on next update. If you or someone you know has duplicate phone numbers, please have them open up a support ticket with their CitizenID attached to the ticket so we can fix the phone numbers for them.

**Comment by AshlynTV** [comment]
This was not fixed lol

**Comment by badcodestv** [comment]
Well, from the end of making a new character, it's fixed. But current characters - I'll need to know who in the city has the same numbers so I can change it for them.

**Comment by AshlynTV** [comment]
Jerry Tickles is the other person. Have not been able to find him in the city at all.  change his though not mine hehe
