### ISSUE TITLE
[Bug] House Menu Issue

### ISSUE THREAD

**Issue by Rea3perPr0** [FrenzyRoleplay/server-issues#425]
**Describe the bug**
I bought a house recently and the Realestate Agent told me that the F1 House menu was bugged. So i checked back after the update yesterday / this morning and saw that the house menu is still bugged for me. Means it opens outside the house when i am infront (All interactions such as locking etc. are working) but as soon as i enter it is no longer in my F1 Menu so i cant open it, place my wardrobe, stash or logout position.

**To Reproduce**
1. Go to your House
2. Click on F1 muscle to open the house menu.
3. Enter your House.
4. Click on the F1 muscle again to open the house menu
5. See no house menu available.

**Expected behavior**
Usually, about what I've been told house menu is supposed to open so you can place your storage, wardrobe and logoff place when you are inside your house. But as soon as i enter the House the F1 menu seems to forget that i am in or near that house. Maybe this has something to do with the rewrite / changes to the F1 menu.

**Comment by badcodestv** [comment]
This has been recently patched.
