### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by TLCFanboy** [FrenzyRoleplay/server-issues#433]
**Describe the bug**
When I disconnect from the FrenzyRP server, my character disappears from the character list. I've created 3 new characters so far and they've all disappeared by the time I reconnect to the server.

**To Reproduce**
1. Log out of the server.
2. Connect to the server.
3. Attempt to select character #1
4. No characters have been created.

**Expected behavior**
My character to show up after I have created it and got a job.

**Screenshots**
![image](https://user-images.githubusercontent.com/81847031/113470139-3c36fb80-9421-11eb-9ef8-23293e4568e3.png)

**Additional context**

**Comment by katahtonic** [comment]
if you have any non-english letters in your steam name, it causes some problems with saving to the DB at this time
