### ISSUE TITLE
[Bug] coke disappearing

### ISSUE THREAD

**Issue by PhantomFPS** [FrenzyRoleplay/server-issues#441]
**Describe the bug**
Used BORAX on a small brick of coke to make 25 baggies i went to put the 25 baggies in my pocket and it only gave me 1 baggy and the rest disappeared.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by badcodestv** [comment]
This is actually working as intended. Just make sure you put  "25" in the input in the middle and not "1".

**Comment by PhantomFPS** [comment]
So basically your fucked when u mess it up your first time.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by badcodestv** [comment]
Unfortunately, yes. Technically speaking, whoever sold you the coke should've told you IC how to break it down correctly.

**Comment by PhantomFPS** [comment]
All good, they told me how to break it down just forgot to tell me it would dissappear if u don't grab all of it but I know now I guess

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by badcodestv** [comment]
We'll consider changing this in the future, but as of right now, just be careful on how you craft drugs.

**Comment by PhantomFPS** [comment]
Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
