### ISSUE TITLE
[Bug] The Ocelot Ardent vehicle has functioning machine guns in the front bumper.

### ISSUE THREAD

**Issue by Kazuhira925** [FrenzyRoleplay/server-issues#443]
**Describe the bug**
This isn't so much of a bug but just a heads up, I just bought the Ocelot Ardent car and it has working machine guns.

**To Reproduce**
1. Go to PDM
2. Click on the sports classic catalogue
3. Scroll down to ARDENT

**Expected behavior**
The car will shoot when you press RMB with no weapon equipped, the guns have unlimited ammo (i think)

**Screenshots**

**Additional context**
I would like to keep the car if possible, the guns should just be turned off ASAP.

**Comment by katahtonic** [comment]
removed
