### ISSUE TITLE
[Feature] - Uptown Riders MC Request

### ISSUE THREAD

**Issue by teucee** [FrenzyRoleplay/server-issues#452]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

N/A

**Describe the solution you'd like**

Hello I’d like to ask if it’s possible to form a Street Bike MC under the name “Uptown Riders”. Our OG got shot down in Liberty City over a gun run gone bad and I was next in line. We noticed this city doesn’t have our logos for Vests / Street bike Jackets so we would like to request those. We are known for our Dinka Double T sports bike any way we could import that from Liberty City? If you need the logo for anything I can provide that in a high resolution I was a graphic designer for Pisswasser living a normal life until this mess came about. We would also like a clubhouse of some sort with mechanic features if possible where all the members can share a stash. 

Click this link, We made the news. 
- https://youtu.be/nZn5S2ClwG4

**Describe alternatives you've considered**

We have been recruiting and riding Bati sports bikes around the city. But we would like to be able to identify ourselves with our logo. 

**Additional context**

![6B6054B6-5A79-4432-A172-29CDE3B74DAB](https://user-images.githubusercontent.com/82058315/113775733-24989500-96f7-11eb-87f9-1928a669c6e6.jpeg)
![1DC771DA-90CF-42FF-8268-D1EBDAF5717E](https://user-images.githubusercontent.com/82058315/113775738-25c9c200-96f7-11eb-9752-6cb12602ecc0.jpeg)

**Comment by teucee** [comment]
![Uptown-Riders-Logo_2 (2)](https://user-images.githubusercontent.com/82058315/114102459-58a9bc80-9895-11eb-8996-c3396999053f.png)

**Comment by ProximateTv** [comment]
I'll see if I can find a good vest to put this on. Do you have any female member and do you want patches on the front showing ranks?

**Comment by teucee** [comment]
Sweet! Yes can you do the traditional MC ranks but instead of President can we do “OG” for my vest. Also yes we do have one female member so far. Can we use the logo on the street bike jackets? Lastly could you made the black letters white so it stands out better? Thank you for replying we are EXTREMELY EXCITED! ❤️

**Comment by teucee** [comment]
![UptownRiders-GTAV-Logo](https://user-images.githubusercontent.com/82058315/114105411-b1c81f00-989a-11eb-8a3f-221260585f46.png)

**Comment by teucee** [comment]
Is it possible for us to get our own hangout spot kind of like the lost?

**Comment by nixety** [comment]
Thanks for this.
I recently built a MC compound at yellow jacket inn, this is a non-branded biker hangout which I believe is occupied by the Grim Reapers. If they are not using it (I think they migrated to the city/tuner shop area) then find out in RP about it. I appreciate this is wanted for your RP immersion but we currently have x2 biker compounds and a third will need to be justified.

**Comment by teucee** [comment]
Ok, I'll check it out through RP. My justification for the compound is the
ability for members to share a stash without it interfering with personal
ones.
