### ISSUE TITLE
[Bug] Noclipping ban when inside of a trunk

### ISSUE THREAD

**Issue by Twistedbitt** [FrenzyRoleplay/server-issues#466]
**Describe the bug**
I was inside of a trunk going with some people to get my car, and i got banned for "no clipping" when i was in the trunk

**To Reproduce**
1. Go to '...' any trunk
2. Click on start the car
3. just drive fast
4. Banned

**Expected behavior**
While in the trunk of a car at high speeds the anti cheat will see you as noclipping and ban you, as it did to me.

**Screenshots**

**Additional context**

**Comment by katahtonic** [comment]
this was resolved
