### ISSUE TITLE
Unlimited Gold Bars [Bug] 

### ISSUE THREAD

**Issue by itslilbuddy** [FrenzyRoleplay/server-issues#487]
**Describe the bug**
I went to sell 2 gold bars at the Paleto Bank, and after selling them I noticed I could still see the option "Sell Gold Bars" which used to disappear after you sold the ones you had on you. Come to find out you can sell unlimited gold bars without even having them on you anymore. Feel free to take the extra 10k I got, I was just testing to make sure I wasn't going crazy. After this clip, I drove away and came back to see if I could still sell more after leaving the area, and got the message "You don't have any gold bars on you. So once you leave without a gold bar on you, you cannot come back to sell more non-existent bars. If you stay  after you sell the ones on you, I'm sure you can sell as many as you want until you leave the area. I didn't test how many times I could do it because I don't want to end up abusing something.
**To Reproduce**
Just go to the bank with a gold bar and sell it. You will be able to sell more after the ones in your inventory are gone. 
**Expected behavior**
For it to be fixed.
**Screenshots**
Sorry medal audio is so shit, have the volume turned down all the way or very low to avoid hearing blasted static.
https://medal.tv/clips/49275628/d1337nmOBt26
**Additional context**

**Comment by itslilbuddy** [comment]
Sorry medal audio is so shit, have the volume turned down all the way or very low to avoid hearing blasted static.

**Comment by cademullen** [comment]
Has been fixed.
