### ISSUE TITLE
Aim, then pull out your gun, you can see in 3rd person to shoot.

### ISSUE THREAD

**Issue by TechKiller09** [FrenzyRoleplay/server-issues#50]
**Describe the bug**
https://www.youtube.com/watch?v=RcV9JGR93WI&ab_channel=Narmik

**To Reproduce**
This allows players to shoot in third person view while in a car.

This issue was brought to me by "MCnarmik
#5825" In discord

**Comment by Cyntaax** [comment]
@badcodestv was this resolved with https://github.com/FrenzyRoleplay/server/commit/886596a77e64dd9bf239719e51f4936e06c5ea88 ?

**Comment by yukisho** [comment]
This has been resolved.

**Comment by katahtonic** [comment]
issue resolved
