### ISSUE TITLE
Emote cannot be done at this time [Bug] 

### ISSUE THREAD

**Issue by Iluzion912** [FrenzyRoleplay/server-issues#500]
Sometimes when someone does a emote at a certain time it says that it cannot be done at this time. I don't know if there is any possible solution to this just wanted to point it out if this was not found out about yet

**Comment by katahtonic** [comment]
when you're in a car or otherwise preoccupied, you're unable to do do emotes. please reopen with a specific example if you think it shouldn't be blocked
