### ISSUE TITLE
[Feature] Ammunation Franchise Owner.

### ISSUE THREAD

**Issue by teucee** [FrenzyRoleplay/server-issues#503]
![image](https://user-images.githubusercontent.com/82058315/114813464-28c05480-9d80-11eb-9d02-a780a683697d.jpeg)

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

At the moment I've realized that the government is the only one that can issue fire-arms licenses. Ammu Nation has been the leading retailer of weapons in the city of Los Santos since 1963, Providing only the best weaponry to the people of Los Santos. We aim to put a gun in every man, woman and child’s hand. We believe that everyone has the right to arm themselves and we are here to help. 

**Describe the solution you'd like**

I'd like to be able to run the main Ammunition store when I am in the city and be able to issue licenses after clearing civs of their CCW license course. This could be implemented with a citizen passing a quiz on the Ammunition's Discordia thread. Below in the comments I have attached a cool script that allows this to be more of a grind. We would use the Armored truck to go out on supply runs to craft weapons.

I would like to main this at the start and speak about possibly hiring employees to make sure this is being ran correctly.

I would like an option to repair weapons as well in exchange for a fee.   

I also would like to conduct shooting range tours where customers will have the ability to use Restricted weapons at our authorized Range for a once in a life time experience using weapons not available to the general public.

I'd also like to supply Legally licensed citizens of Los Santos with an array of weapons from melee weapons, possibly a Glock 19 unique to our store and possibly a Shotgun for home defense/hunting? Also unique to our store.

Running this would be no problem as I am on every single day for hours on end. 

**Describe alternatives you've considered**

I have been roleplaying this but it is not possible to live out my RP without the ideas mentioned above as I don't feel comfortable selling weapons licensed to myself. This has been on my mind since I got here 4 months ago, now that I have an understanding and feel for how the city works I would totally like to run my own business. 

**Additional context**

![image](https://user-images.githubusercontent.com/82058315/114813288-ca937180-9d7f-11eb-8ff5-63de82c799e6.jpeg)

I have found this cool script that turns this idea into a proper grind. Could we have the Ammunation armored truck as well? -

Ammunation Store Owner Script — https://forum.cfx.re/t/release-b1g-ammujob-ammunation-job-with-with-weapon-pieces-system/652974/6

**Comment by teucee** [comment]
I have thought about this and it would work if I could just run it out of one store. The store by the beach on the left side of the map next to the tattoo shop and clothing store would be cool.

**Comment by teucee** [comment]
An easy way to make acquiring the weapons would be to craft them through having materials, this way it ties into the whole "Gun Smith" purpose and it helps the economy. It but be like a Tuner shop but for guns and knives and other legal items.

**Comment by teucee** [comment]
It would be helpful to have limited MDT access as well for background checks.

**Comment by teucee** [comment]
If multiple stores isn't an option. The store on Great Ocean Highway would be the perfect place as the plaza is very spacious and people rarely drive up this way unless it's to go fishing. It would also be cool to serve as a hub for fishing and hunting licenses.

**Comment by teucee** [comment]
An easy way to make acquiring the weapons would be to craft them through having materials, this way it ties into the whole "Gun Smith" purpose and it helps the economy. It but be like a Tuner shop but for guns and knives and other legal items.

**Comment by teucee** [comment]
If multiple stores isn't an option. The store on Great Ocean Highway would be the perfect place as the plaza is very spacious and people rarely drive up this way unless it's to go fishing. It would also be cool to serve as a hub for fishing and hunting licenses. This way DOJ and Law Enforcement cant focus on more important things.

**Comment by teucee** [comment]
I have found this cool script that turns this idea into a proper grind. Could we have the Ammunation armored truck as well? -

Ammunation Store Owner Script — https://forum.cfx.re/t/release-b1g-ammujob-ammunation-job-with-with-weapon-pieces-system/652974/6

**Comment by teucee** [comment]
I have been using The store on Great Ocean Highway in my RP. It would be the perfect place as the plaza is very spacious. It would also be cool to serve as a hub for fishing and hunting licenses. This way DOJ and Law Enforcement cant focus on more important things

**Comment by PeterZeee** [comment]
make the armoured ammunation truck robbable too for extra RP. Pay for security and protection while escorting weapon deliveries

**Comment by teucee** [comment]
An easy way to make acquiring the weapons would be to craft them through having materials, this way it ties into the whole "Gun Smith" purpose and it helps the economy. It would be like a Tuner shop but for guns and knives and other legal items.

**Comment by teucee** [comment]
Another cool way to make this Ammunation stand out is by putting in a "Glock 19" That can be one of the weapons crafted through material farming and can only be acquired through the shop. The weapon can do the same damage as the Baretta but maybe a better range increase? Also, for the gunsmith menu we can use one of the counters to repair the weapons through having materials.

**Comment by teucee** [comment]
Using the main Ammunation in the city and implementing a script where employees can allow users to use the range for a fee would also be another great way to create RP. This store would actually be ideal as it is pretty spacious and can accommodate things such as a "Gun smith bench" instead of using a counter.
