### ISSUE TITLE
[Bug] Tow truck job is bugged

### ISSUE THREAD

**Issue by MrGaryKing** [FrenzyRoleplay/server-issues#519]
**Describe the bug**
I can't become on duty tow truck driver and earn a salary. I tried swapping jobs and going back to towing, I've tried relogging, I've tried different tow drucks and it still always tells me im off duty on my phone. In the chat if I type /jobs it days I'm on duty.

**To Reproduce**
1. Go to '...' No idea I think I'm the only one affected by it

**Expected behavior**
Select towing as your job and become on duty and start earning a salary

**Screenshots**

**Additional context**

**Comment by katahtonic** [comment]
not seeing a problem, its not a whitelisted job, its a "go do something" job
