### ISSUE TITLE
General Manager Position[Bug] 

### ISSUE THREAD

**Issue by Trimmarius** [FrenzyRoleplay/server-issues#52]
**Describe the bug**
Jack (nixety) informed me that the city wanted my Citizen ID so that I could be certified to help at the shop. When I took a nap to see if I could access the workbench I couldn't. And when he mentioned it might be passed to me at storm it still has not came through.  He said for me to put in a ticket because he believed I would be able to. Just let me know if I need to provide anything.

**Comment by badcodestv** [comment]
What is your citizen id?

**Comment by Trimmarius** [comment]
IVO50267 is my citizen ID.

**Comment by Trimmarius** [comment]
So maybe because I was on the mechanic job the job never came through. So I am currently unemployed in the case if you try and get me job it should come through. Let me know whenever you push it through so I can make sure I got the job. This is the last thing me and Jack could come up as a solution.
