### ISSUE TITLE
Toyota Supra Tuning[Bug] 

### ISSUE THREAD

**Issue by Trimmarius** [FrenzyRoleplay/server-issues#53]
**Describe the bug**
The Toyota Supra in the city needs to be retuned. Right now I am the only one in city who somewhat regularly drives the Supra and the others belong to people who are not in the city as much. Right now the Supra seems that it has almost the same tuning as the Jester Classic. 

**Expected behavior**
I would say that a Joyride Import that costs 400k+ would be somewhat better than the local version of the car. The Jester Classic cost around 110k and the Supra was 400k+. I am not looking for something that goes way to fast just something that instead of almost capping above 200 maybe capping 240-250 mph when fully upgraded.

**Additional context**
Based on some speed test I did whenever I was comparing the Jester Classic and the Supra they are the same with lvl 3 transmission, lvl 3 suspension, stock brakes, turbo, with the only difference is the Jester Classic has lvl 3 engine and the Supra has a lvl 4 (illegal engine). Below are some clips from Twitch that hopefully demonstrate that the tuning is close to the same for the Supra and the Jester Classic.

Supra Upgrades
https://clips.twitch.tv/EncouragingSlickLegCclamChamp
Jester Classic Upgrades
https://clips.twitch.tv/NastyDiligentCroissantBudStar
Supra Sprint
https://clips.twitch.tv/CloudyImpossibleCourgetteOhMyDog
Jester Classic Sprint
https://clips.twitch.tv/NeighborlyAbstruseCookieAMPEnergy
Supra vs J Classic
https://clips.twitch.tv/BrainyPlumpLobsterDoggo

**Comment by yukisho** [comment]
This has been resolved.
