### ISSUE TITLE
[Bug] [Feature] Emote fixes and adds

### ISSUE THREAD

**Issue by jeebbers** [FrenzyRoleplay/server-issues#534]
**Describe the bug**
I am not sure if this is a bug because I heard it was purposely like this, but I heard it the other way around as well. The emotes where you lay down only let you stay down for a couple seconds and automatically pops you back up. Examples: sleep, _sunbathe_(s), _prone_, _passout_(s), etc. Also, there is multiple emotes that us females are not allowed to use because we are not male: _leaf blower_, _BBQ_, _beg_, _musician_, _cop beacon_(s), etc. I understand this is a FiveM / GTA restriction they put on these emotes but I just thought I would add it in here to see if there was a way around it. A _carry_ emote would be really fun as well. I have seen that in many servers before and can create some fun RP scenarios if used appropriately.

**To Reproduce**
1. type /e _sleep; sunbathe; prone; passout_
2. Character does emote
3. Character stands back up after a couple seconds of doing the emote, automatically.
4. See error ^

**Expected behavior**
When you do the emote your character will stay in that emote until it is cancelled. Similar to the meaning of inertia... the tendency of a body at rest to remain at rest (or of a body in straight line motion to stay in motion in a straight line) unless acted on by an outside force. So, for example getting punched, kicked, or even run over.

**Additional context**
For only being in the server for a short amount of time, I had to pass on many different RP opportunities because you can not lay down for more than 5 seconds. It would bring another level of RP with these emotes working the correct way. Same goes for the emotes that only males can use with females being able to use them as well and adding a _carry_ emote.

P.S thanks for being the BEST server I have been a part of so far. I love the efficiency and communication from the staff team. It's something I have never seen before within another community.

**Comment by cademullen** [comment]
Should be fixed now.
