### ISSUE TITLE
Tattoo issues

### ISSUE THREAD

**Issue by Nussifer** [FrenzyRoleplay/server-issues#54]
**Describe the bug**
I have an issue where I can only have tattoos on one arm and leg 

**Expected behavior**
I change the number on the right arm and right leg but nothing is showing up

I have re-logged and tried it again and it didn't change anything

**Comment by badcodestv** [comment]
Mind showing us a video?

**Comment by Nussifer** [comment]
I recorded a video but its not the right type to upload

**Comment by Reaper6six6** [comment]
I had the same issue today. I was able to apply torso and left side tattoo's only.

**Comment by katahtonic** [comment]
fixed MR #120
