### ISSUE TITLE
Instead keys [Bug] 

### ISSUE THREAD

**Issue by poppipikjl** [FrenzyRoleplay/server-issues#549]
Describe the bug
If you go to any kind of vehicle and press search (H) and wait until you get the option to hotwire or search, when this appears click hotwire then go to car option and start the engine. now you have keys to every car you can go up to any local and get in and drive away

To Reproduce
Steps to Number 2:

Enter any vehicle 
Click Search
wait til you get the option again
now click hotwire
now go to vehicle option and start engine

**Comment by katahtonic** [comment]
fixed
