### ISSUE TITLE
Not able to read text messages once message is opened[Bug] 

### ISSUE THREAD

**Issue by DeviLzFury** [FrenzyRoleplay/server-issues#55]
**Describe the bug**
When i get a text message i am unable to see it when i open up the message.  I can see the message partly in lists of text but when i go to click on it to open it larger and reply nothing there

**To Reproduce**
1. Go to 'Phone after getting a text'
2. Click on 'message from person who texted'
3. Scroll down to 'N/A'

**Expected behavior**
When getting a text should be able to open the text and see full message from where you can then reply

**Screenshots**

**Additional context**

**Comment by badcodestv** [comment]
Mind providing screenshots?

**Comment by DeviLzFury** [comment]
![20210105144354_1](https://user-images.githubusercontent.com/76492631/103775692-0cc84c80-4ff4-11eb-8704-5746982b682d.jpg)
![20210105144359_1](https://user-images.githubusercontent.com/76492631/103775697-0df97980-4ff4-11eb-906b-70aad1f22221.jpg)

1st pic is to show text message when i open up messages.  Second pic is when i select a person message to open it to read it.

**Comment by DeviLzFury** [comment]
Forgot to say also I think I've had this issue since we got the new phones in city. If not since then shortly after.

**Comment by katahtonic** [comment]
resolved as of 3/4 please reopen if you continue to see an issue
