### ISSUE TITLE
[Feature] Extend Lock distance DOC Big Gates

### ISSUE THREAD

**Issue by Trauma-Llama** [FrenzyRoleplay/server-issues#563]
**Is your feature request related to a problem? Please describe.**
Before the changes to the gates it was fairly easy to drive through the gates and have the gate close and be able to lock it. Now due to the distance the gates will open/close and its tough to close them properly 

**Describe the solution you'd like**
Just an increase in the range for the lock distance.

**Describe alternatives you've considered**
Leave it the way it is? it's still doable just kind of a pain.

**Additional context**

**Comment by orakah** [comment]
@Trauma-Llama you are talking about the front gates right? this ones > https://i.imgur.com/Nnr2xiv.jpg

**Comment by Trauma-Llama** [comment]
Yup, those ones.

**Comment by orakah** [comment]
Should be in next restart, please test it and give me feedback

**Comment by Trauma-Llama** [comment]
Distance is better now, Had a weird thing happen though where 2 people were trying to go either way and the gates prompt wouldn't show up.
(Large gates again)
I was going out of the prison and opened the inner gate.
The other person was coming in and opened the outer gate
Prompts wouldn't show up for a bit till it seemed like we went back to our original gate.
But I do believe that was a rare occurence that happened. If it becomes a problem I'll open another ticket

Thanks for the quick reply Orakah :)

**Comment by orakah** [comment]
I had to reduce the zone a little bit, because the cars are so fast that the zone didn't have time to register you leaving her. The zone is still bigger than before the changes, if you find any bug let me know.
