### ISSUE TITLE
[Bug] Off Duty Mechanics - LOWER PAY CHEQUE

### ISSUE THREAD

**Issue by liddoshauna** [FrenzyRoleplay/server-issues#598]
**Describe the bug**

$17000 was earned in a day by an OFF-DUTY Lead Mechanic paycheque at $125

Please lower the amount OFF-DUTY Mechanics can get. There are a lot of Mechanics who take time off, but are still able to rack up their money just by being off-duty...

**Comment by Reaper6six6** [comment]
I think the off duty pay of DOJ is the same way as well, but I could be mistaken. Mechanic might be by design though since like car sales and realtors, it's primarily a commission based job.
