### ISSUE TITLE
[Bug] All purchased guns have the same serial throughout restart

### ISSUE THREAD

**Issue by yukisho** [FrenzyRoleplay/server-issues#60]
**Describe the bug**
Weapons of the same type purchased from Ammunation all have the same serial number. No matter who buys a gun, everyone will get the same serial number of gun. So during an entire restart, every person who purchases a Walther P99 will all have the same serial number. Same goes for the Vintage Pistol etc.

**To Reproduce**
1. Go to any Ammunation
2. Buy a gun
3. Check the serial and close the store
4. Open the store again and the same gun type will have the same serial.

**Expected behavior**
New serial number for each gun purchased.

**Screenshots**

**Additional context**

**Comment by katahtonic** [comment]
issue resolved
