### ISSUE TITLE
Race app

### ISSUE THREAD

**Issue by PunisherInOKC** [FrenzyRoleplay/server-issues#61]
**Describe the bug**
On southisde suicide, Grapeseed loop, grand prix short and vinewoood tour the fastest laps are zero seconds. 

**Expected behavior**
An actual time should be recorded. 

**Additional context**
I'm thinking that this is caused by someone starting a race then ending the race.  I've been unable to recreate how they got the time of zero.

**Comment by katahtonic** [comment]
issue resolved
