### ISSUE TITLE
[Feature] Allow bank transfers from the phone. 

### ISSUE THREAD

**Issue by Reaper6six6** [FrenzyRoleplay/server-issues#610]
**Is your feature request related to a problem? Please describe.**
No issue, but would like to see a mobile banking app that would allow you to transfer money from your phone. 

**Describe the solution you'd like**
Please, if possible, create a banking app or an option within the information that shows your current bank balance that would allow you to wire money directly from your phone. 

**Describe alternatives you've considered**
If not through the phone, maybe adding a /banktransfer command that would allow you to put in the players ID and amount after to "wire" them money without the need to be at a bank. 

**Additional context**

**Comment by katahtonic** [comment]
we've discussed this multiple times, and we've decided to not allow transfers over your phone
