### ISSUE TITLE
[Bug] Ability to go through objects via emote

### ISSUE THREAD

**Issue by yukisho** [FrenzyRoleplay/server-issues#62]
**Describe the bug**

**To Reproduce**
1. Walk up to a wall/fence
2. Turn around and face away from it
3. Use /e sunbathe3
4. Mid animation use /e c

**Expected behavior**
Not phase through objects

**Screenshots**
https://streamable.com/7hw9p8

**Comment by katahtonic** [comment]
just... dont?
