### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JinxLiam** [FrenzyRoleplay/server-issues#63]
**Describe the bug**

There is a bug where when I get my Sultan from Garage E, it cannot be seen by other people. It shows me just going up and down through the ground as I drive.

**To Reproduce**
1. I always grabbed my Sultan from Garage E
2. Take out the car
3. Other people see that there is no car there

**Expected behavior**
I believe that people should be able to see my car.

**Screenshots**

**Additional context**

**Comment by katahtonic** [comment]
issue resolved
