### ISSUE TITLE
[Bug] Inventory being huge and out of lined 

### ISSUE THREAD

**Issue by SwampiePrincess** [FrenzyRoleplay/server-issues#655]
![20210524160710_1](https://user-images.githubusercontent.com/78699161/119409298-b27f0e00-bcac-11eb-9a60-9017bdf5bf3d.jpg)

the middle is not in the middle
rows of 3 is not cutting it. rows of 5 is good

- its unique as its circles and it being so big is not user friendly
- the rows don't even out correctly
![20210524162753_1](https://user-images.githubusercontent.com/78699161/119409497-04279880-bcad-11eb-8ffb-99670d1c21a0.jpg)

if the rows were 4-5 and smaller it be awesome

**Comment by katahtonic** [comment]
resolved
