### ISSUE TITLE
All top right Notifications don't pop up

### ISSUE THREAD

**Issue by Incern** [FrenzyRoleplay/server-issues#657]
Before you would get a notification top right saying 'Receiving a call from Meeks' Same for when you join and leave a radio it would say 'joined radio 69' 'left radio channel' but they don't seem to be popping up. https://streamable.com/kvm6pg

**Comment by Incern** [comment]
Just figured i think this is all notifications including bleeding out, stress relieved etc.

**Comment by katahtonic** [comment]
fixed
