### ISSUE TITLE
[Bug] As a mechanic, I can see the realtor app on the phone. 

### ISSUE THREAD

**Issue by Reaper6six6** [FrenzyRoleplay/server-issues#659]
**Describe the bug**

**To Reproduce**
1. Be a GM at the Paleto Garage
2. Open your phone
3. Click on and open the realtor app.
4. See issue

**Expected behavior**
Only realtor's should see this. 

**Screenshots**
![image](https://user-images.githubusercontent.com/77019757/119430928-a1032980-bcdf-11eb-9e87-b874a9f99107.png)
**Additional context**

**Comment by katahtonic** [comment]
fixed
