### ISSUE TITLE
[Feature] Show Some TLC for the Casco

### ISSUE THREAD

**Issue by fervunk** [FrenzyRoleplay/server-issues#669]
**Is your feature request related to a problem? Please describe.**
The casco is a great, powerful and classic sports car incapable of beating a 4 ton 2001 dogmobile sedan. I understand the needs of design and balancing in an online MP game but when the balancing creates results such as sports cars being slower than cheaper sedans and local's cars then it becomes a problem.  the casco currently is only capable of around 115 mph. my Vapid steiner, a 9500 sedan with a lvl 1 engine upgrade can easily smash 135+ on the highway.

**Describe the solution you'd like**
TO be short, i would like just the top speed to be increased to around 150-160. if some love could be given to the brakes and acceleration that would be great too. but its mostly the top speed that lets it down.

The car is based on a Maserati 3500 GT which STOCK has a 3.6 liter 220hp V8 and is capable of 150 mph. i believe that at the minimum the in game represention especially after being upgraded with LVL 3 engine, Turbo, Transmission, and suspension upgrades should reach at least the same speed. 

**Describe alternatives you've considered**
Not many. i am not a developer or game designer but i imagine it not being too too diffcult to change one cars top speed by around 30 mph.

**Comment by nixety** [comment]
Closing this as the changes will go live. thanks
