### ISSUE TITLE
[Bug] Hunting Knife Bug

### ISSUE THREAD

**Issue by hhenry12** [FrenzyRoleplay/server-issues#674]
**Describe the bug**
When you're hunting and trying to slaughter a deer, the server would say that "You need a knife" when you do have a knife. I think this was a bug when the hunting system got rework because I was testing it out after the upset, I cannot confirm this happened prior to the server coming back and before the hunting rework. I can confirm the hunting system was working before it went down

**To Reproduce**
1) Start the hunting job
2) Kill at least one deer
3) Pull out the knife 
4) Attempt to Slaughter the deer
5) Realize the server message

**Expected behavior**
After pulling out the knife, the user would be able to slaughter the deer without any issue. The progress bar would appear when slaughtering the animal.

**Screenshots**
https://i.imgur.com/I5ANtuu.jpg

**Additional context**

**Comment by katahtonic** [comment]
should be resolved. reopen if there's any further issues with it
