### ISSUE TITLE
[Bug] Hair, skin and beard changing

### ISSUE THREAD

**Issue by IkClout** [FrenzyRoleplay/server-issues#69]
Bug: whenever i login my characters skin color is default, no bread and my hair color changes every time i look at my hair at a different angle. I've gone to the barber and changed stuff but it never saves. Every time i load into the server it's messed up. 

https://gyazo.com/c93ca9f37d351855010610ba1706ce4c
https://gyazo.com/9c00533f7ccffafdab2c38cb24c424b3

**Comment by AngryBaconator** [comment]
This is due to the amount of people in the city. You can roll with it, or try resetting your ped if you want to look normal look that bad. It is up to you. Devs are looking into it.
