### ISSUE TITLE
[BUG] House Removal Request

### ISSUE THREAD

**Issue by theCitizen420** [FrenzyRoleplay/server-issues#7]
**Describe the bug**
Joseph Cooper [ID: GOK42823] has a home at Baytree Canyon Rd7 is related to the /removehouse issues from months back. When he wakes up at the house, he wakes up down the street and not at the intended location. There MAY be another house ID'd as Baytree Canyon Rd7 (owned by someone else). The "may" exists due to the /removehouse command. The problem, in addition to above, that he experiences is flickering furniture. 

**To Reproduce**
1. Wake up at Baytree Canyon Rd7
2. Leave the house
3. Wrong place

**Expected behavior**
Standard house functionality

**Additional context**
Cadillac Koopa#5756 on Discord for more information.

**Comment by badcodestv** [comment]
Can you have Koopa remove any items in his stash? We will completely remove this from the database and have Real Estate re-add this.

**Comment by theCitizen420** [comment]
Sorry for the delay. I must've missed the email notification. The stash should be clear and is ready to be removed.

**Comment by theCitizen420** [comment]
Has this been removed? Coop has contacted me since.

**Comment by theCitizen420** [comment]
It seems like @badcodestv has removed the house. Closing this.
