### ISSUE TITLE
car payment

### ISSUE THREAD

**Issue by Gr1zzlyAdams** [FrenzyRoleplay/server-issues#70]
when i go on my phone to make a payment on my comet sr, i click on the payment and it takes me back to the list of cars that i have on the vehicle app. it does not make the payment and does not give me any f8 errors either. i have went to a judge to retransfer the car to me and it still does the same thing. the judge also transferred it into someone elses name and then transferred it back into my name and it still does the same thing as described above

**Comment by Wollffus** [comment]
Where did you originally get the vehicle?

**Comment by katahtonic** [comment]
issue resolved
