### ISSUE TITLE
Removal of Bugged Car that was Bought 

### ISSUE THREAD

**Issue by Trimmarius** [FrenzyRoleplay/server-issues#700]
**Describe the bug**
When I bought a Moonbeam Lowrider I somehow signed for two of them. Spawning in two when bought. In this post is a link for the first bug report I put.

**To Reproduce**
Reference other post mentioned below for how it came about.

**Expected behavior**
I do not really care for the money reimbursement I just want to go ahead and get it removed from my list of cars. If repos are going to happen eventually it doesn't matter but if there is no major plans for it I would like it to be removed. The Moonbeam Lowrider has the license plate 8JI883PH and is stored at Garage E. 

**Additional context**
First Post:
https://github.com/FrenzyRoleplay/server-issues/issues/679

**Comment by orakah** [comment]
@Trimmarius the extra vehicle should be removed from your garage.
