### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Skywolfie** [FrenzyRoleplay/server-issues#73]
**Describe the bug**
i've  been noticing that my food and water never give me full satisfaction. when i eat either double double or madrinas

**Screenshots**
![bars](https://user-images.githubusercontent.com/76183975/103961228-53cd5380-5154-11eb-81f6-7be781285f08.JPG)

**Comment by yukisho** [comment]
Do you play at 1440p or above?

**Comment by Skywolfie** [comment]
> Do you play at 1440p or above?

yes i do play on a 2560 x 1440p resolution

**Comment by yukisho** [comment]
That would be the issue. The HUD currently is not optimized for resolutions over 1080p. However, it may be changed in the future.

**Comment by katahtonic** [comment]
issue resolved - new hud
