### ISSUE TITLE
[Bug]  People Can use the realtor app

### ISSUE THREAD

**Issue by steeledashow** [FrenzyRoleplay/server-issues#743]
If the Realtor app shows up when you fly in you can set houses. I tested it and it works. Tho I accidently placed a house and I couldnt remove it. I was testing it and wasnt sure if it would work and it did.

**Comment by Nussifer** [comment]
the app showed up for me then i closed my phone and reopened it and it was gone

**Comment by katahtonic** [comment]
fixed for next storm
