### ISSUE TITLE
Inmates inventory staying [Bug] 

### ISSUE THREAD

**Issue by Nussifer** [FrenzyRoleplay/server-issues#77]
**Describe the bug**
An inmate was sent to prison with all his inventory still on him

**To Reproduce**
Don't know if it was a one-off or not 
**Expected behavior**
All items are taken tell they are released 

**Screenshots**
![Screenshot_97](https://user-images.githubusercontent.com/69865982/104266704-59c17e00-544d-11eb-8a9d-bb4c422c068d.png)
these are some of the items he had on him

**Comment by Wollffus** [comment]
We will look into this issue, and appreciate that you are bringing these to git. Thank you very much

**Comment by katahtonic** [comment]
issue resolved
