### ISSUE TITLE
[Bug] Local PD cars spawning at pd and disappearing 

### ISSUE THREAD

**Issue by IkClout** [FrenzyRoleplay/server-issues#78]
**Describe the bug**
When i go to the parking garage at PD and look around at different angles,  gta5 local pd cars show up and go away. 

**To Reproduce**
1. Go to PD parking lot
2. Click on look around at different angles

**Screenshots**
https://gyazo.com/e784cb178cb109df32b160a411b53b2b

**Comment by Wollffus** [comment]
We will look into the clean up of the local cars and see what is causing this. Thank you for bringing issues to our attention.

**Comment by katahtonic** [comment]
should not be an issue anymore
