### ISSUE TITLE
[Bug] Officer select in MDT

### ISSUE THREAD

**Issue by IkClout** [FrenzyRoleplay/server-issues#82]
**Describe the bug**
When i add officers in the MDT and save it for some reason the officers i added get removed when i save it. Also if i try to edit it and add the officers back and save it, it still doesn't add it. Started noticing this issue yesterday. 

**To Reproduce**
1. Make a report
2. add officers and save it 
3. then go back to the report

**Screenshots**
In the video you can see the officers involved, Billy O'Connor, Dale Peterson and Paige Turner. When i save and go back, Paige Turner is removed, i try to add it back and once i save it, it removes it again. Clip > https://streamable.com/9su2w8

**Comment by Wollffus** [comment]
We will look into the MDT and appreciate you bringing this to our attention

**Comment by katahtonic** [comment]
issue resolved
