### ISSUE TITLE
Property Taxes [Bug] 

### ISSUE THREAD

**Issue by AngryBaconator** [FrenzyRoleplay/server-issues#83]
**Describe the bug**
Not sure if this is a known issue but I was paying for my property taxes and noticed it said "you owe $1" instead of the normal tax. So I paid it and it only took $1 from my bank. This happened to all the 3 properties I own. I will provide a screenshot below.

**To Reproduce**
1. Go to 'My Keys'
2. Click on 'address/house'
3. Click on Pay Taxes
4. Only pay $1 for taxes for each location

**Expected behavior**
Expected to pay whatever the percentage was that was set for the taxes

**Screenshots**
https://frenzyrp.com/index.php?attachments/tax-png.162/

**Additional context**

**Comment by Wollffus** [comment]
Thank you for putting in this ticket, i have noticed the same and from a realtor in city was told its "normal" so i never said anything. 

We will look into this and if needed, will implement a fix <3

**Comment by katahtonic** [comment]
issue should be resolved
