### ISSUE TITLE
Repair Kits, Seatbelts

### ISSUE THREAD

**Issue by Reaper6six6** [FrenzyRoleplay/server-issues#85]
Latest push seems to keep you trapped in your car if you try and get out but have your seatbelt on. Is this intentional?

Also, latest push seems to remove repair kits and advanced kits after each use now. Is this intentional, and if so, can the cost and supply be adjusted at you took? Would also be nice if the mechanics had a job based repair in their job wheel if these won't be adjusted as it would give them more road side repair RP.

**Comment by AngryBaconator** [comment]
Regular Repair kits have been fixed. 

Seatbelts are intentional. He made it where you have to take off your seatbelt to get out of a car just like IRL
