### ISSUE TITLE
Flash GT speed 

### ISSUE THREAD

**Issue by DigitalPrime27** [FrenzyRoleplay/server-issues#86]
I was told that the Flash GT is supposed to have a top speed of 180 mph as a Joy Rides import. But my Flash GT only has a top speed of 147 mph and that on the highway going downhill with  a stage 2 engine upgrade. MJ-DripLockFresh(Discord)

**Comment by Wollffus** [comment]
We will look into the speeds of the cars and if they are where they should be or not. Thank you for bringing this to our attention and we will get back to you as soon as we can.

**Comment by DigitalPrime27** [comment]
Thanks

**Comment by badcodestv** [comment]
https://github.com/FrenzyRoleplay/server/commit/8ccef1606f0c540d571a56fd9305e6af3b9e1a19

Implemented on next restart
