### ISSUE TITLE
[Bug] LOW PRIORITY - Car color changes not saving.

### ISSUE THREAD

**Issue by unPhiltrd** [FrenzyRoleplay/server-issues#88]
Certain upgrades/changes to vehicle don't seem to be saving.

Example:  After purchasing a car, I went to Benny's to change the colors.  The interior color doesn't seem to save.  Whenever I park the car, the colors return to their original shade. This happens whether or not I stay in or leave the city.  LMK if there is any further testing that you would like me to do.

Thank you.

![Before Park](https://user-images.githubusercontent.com/77427756/104548355-7a244080-55e5-11eb-9047-246bb3f14b77.jpg)
![After Park](https://user-images.githubusercontent.com/77427756/104548359-7db7c780-55e5-11eb-9fda-85f4ef79fe5a.jpg)

**Comment by katahtonic** [comment]
issue resolved
