### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JudgedRAcer** [FrenzyRoleplay/server-issues#91]
**Describe the bug**
i had an extended mag for a pistol and i put it on a combat and when i went to go take it off it said under attachments that this weapon has no attachments on it but it still mad the mag go up from 12 to 16 when it hit r after pulling it out it 
**To Reproduce**
1. Go to put mag on combat 
2. Click on '....' attachments and try to take it off 
3. Scroll down to '....

**Expected behavior**
i expected to put it on and take it off after i put ammo inside of it 
**Screenshots**

**Additional context**

**Comment by katahtonic** [comment]
issue resolved
