### ISSUE TITLE
Add storage slots to apartments stash

### ISSUE THREAD

**Issue by Reaper6six6** [FrenzyRoleplay/server-issues#94]
**Is your feature request related to a problem? Please describe.**
The weight is fine, but it would be nice to have additional storage spots in the apartment storage/stash.

**Describe the solution you'd like**
1-3 more rows, the weight is fine as is.

**Comment by yukisho** [comment]
This may become a thing in the future. However, for now we do not have any immediate plans to increase the slots.

**Comment by badcodestv** [comment]
https://github.com/FrenzyRoleplay/server/commit/ee7b5e07094b6849875b91505cf0d82e886ce470

Implemented on next restart
