### ISSUE TITLE
[Bug] New MDT selection. 

### ISSUE THREAD

**Issue by IkClout** [FrenzyRoleplay/server-issues#98]
When i create a report and select multiple officers, the drop down for the shots fired gets covered up. Also when i go back to edit, the options to chose shots fired, gsr test, and casings don't show up. 

Evidence: 
https://gyazo.com/0c2953a97ff33baae700b6ba61fcee63

**Comment by yukisho** [comment]
Thank you, I will look into this.

**Comment by yukisho** [comment]
A solution has been pushed to live.
