### ISSUE TITLE
Suppressor stuck on weapon

### ISSUE THREAD

**Issue by theabtv** [FrenzyRoleplay/server-issues#99]
**Describe the bug**
Attached a Suppressor to a Walther P99. The suppressor is attached to the weapon according to the description (Screenshot below) however the weapon does not **visually** show the suppressor on there nor does it make the gun silenced. Another issue is that I cannot remove the attachment after putting it on there as it is stuck and does not show that it is there to be removed. (Screenshot also below)

**To Reproduce**
1. Go to 'Inventory and 'use' the attachment (suppressor) while you have your weapon equipped (P99)'
2. Click on 'the weapon from the inventory and click on 'attachments' to see if the weapon has the attachment which it doesn't. However on the description it shows that it does indeed has the suppressor attached.'
3. See error - Attachment does not visually show on weapon. Attachment cannot be removed from weapon.

**Expected behavior**
Visually shows that the weapon has the attachment on there and also makes the gun silenced while the suppressor is attached. 

**Screenshots**

![walther sup] (https://user-images.githubusercontent.com/77626917/104938698-52e3bf80-59a7-11eb-8f63-5b3e063d71cf.PNG)
![image] (https://user-images.githubusercontent.com/77626917/104938732-5d9e5480-59a7-11eb-9d78-b549eac9c35e.png)

**Additional context**

**Comment by katahtonic** [comment]
p99 removed
